### ISSUE TITLE
can't start game in android os

### ISSUE THREAD

**Issue by sunaneko-1324** [OpenRCT2/OpenRCT2#12576]
**OS:** android 10 
**Version:** 0.2.6 stable arm apk
**Commit/Build:** n/a

device : galaxy tab s4

**Steps to reproduce:**
1. install 0.2.6 stable apk
2. create folder /storage/emulated/0/rct2
3. copy original rct2 folder contents
4. start openrct2 at home screen 
5. popup window shown "openrct2 needs files from the original..."
6. when ok touch -> app closed

* If you not copy rct2 folder, popup window shown " .dat file can't find". However, the game will not launch if the rct2 folder is copied.

**Dump file**
part of logcat

08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: Error extracting files
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: java.io.FileNotFoundException: openrct2
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.content.res.AssetManager.open(AssetManager.java:875)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.content.res.AssetManager.open(AssetManager.java:852)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at io.openrct2.MainActivity.copyAsset(MainActivity.java:182)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at io.openrct2.MainActivity.copyAssets(MainActivity.java:168)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at io.openrct2.MainActivity.startGame(MainActivity.java:151)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at io.openrct2.MainActivity.onStart(MainActivity.java:134)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.Activity.performStart(Activity.java:7980)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3646)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.os.Looper.loop(Looper.java:237)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
08-04 02:31:44.685 10305  8942  8942 E OpenRCT2: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Screenshots / Video:**
n/a

**Save game:**
n/a

**Comment by kcotugno** [comment]
Under `/sdcard/openrct2` you need to place `g2.dat`, [`language/`](https://github.com/OpenRCT2/OpenRCT2/tree/develop/data/language), [`shaders/`](https://github.com/OpenRCT2/OpenRCT2/tree/develop/data/shaders), [`objects/`](https://github.com/OpenRCT2/objects), and [`title/`](https://github.com/OpenRCT2/title-sequences). These can also be found on Linux under `/usr/share/openrct2`.

**Comment by hsungha** [comment]
@kcotugno excuse me. The first time you run the game that popup is shown 'could not find /sdcard/rct2/Data/g1.dat at this path'.  so I saved the file to the path shown in the popup. However, the game ends immediately.
how can i fix that ?

**Comment by janisozaur** [comment]
Android port has few users. The harsh truth about the best way to improve it is to work on it yourself.

We might eventually fix that, but historically there's little work going on in that area.

**Comment by Gymnasiast** [comment]
Closing this as it’s an old issue and also seems to be mostly a question, rather than reporting a bug.
