### ISSUE TITLE
Segmentation fault (core dumped) error on linux version

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#13656]
**OS:** Ubuntu 18.04
**Version:** 0.3.2
**Commit/Build:**  556c786

I don't know it is just only my case, or issue can be occured for all of you.
So it could be asking help to you, if so, I feel sorry.

In Ubuntu 18.04 (and seems also 20.04), I met the ``Segmantation fault (core dumped)`` error message when I run ``./openrct2`` via terminal.

**Steps what I did:**
I have no idea if it could be reproducible to you, so I wrote what I did. (Using PPA installed a old network version(0.3.0-7), so I have been using this method)
1. Go to ``/home/orct``,
2. ``wget https://github.com/Limetric/OpenRCT2-binaries/releases/download/v0.3.2-556c786/OpenRCT2-0.3.2-develop-556c786-linux-x86_64.tar.gz``
2. ``tar zpcvf OpenRCT2-(blahblah).tar.gz``
3. ``cp -r ./OpenRCT2/* ./``
4. Copy vanilla's stuff, such as ``ObjData``, ``Scenario`` directory into ``/home/orct``
5. Run ``./openrct2 --verbose`` via terminal. Then I met this (rct1-path is setted, but I don't think it's matter):
 ![image](https://user-images.githubusercontent.com/10726524/103232406-b2891500-497d-11eb-8dd8-0da665754261.png)

I noticed this issue my automated server screenshot system has broken.
I have been taking screenshots of my headless server's auto save files automatically by using cronjob, but ``openrct2-cli screenshot`` feature also returned the Segmentation fault error, so there were no screenshots.

However, just opening headless(e.g. ``./openrct2-cli``) works fine. Never mind about it.

Sorry again if it is just an issue for myself
but if you don't mind, I ask you some help.
If it is truely an issue, phewww, I hope this fix ASAP.

**Comment by janisozaur** [comment]
I believe we build those with symbols, please provide stack trace:
```
$ gdb --args ./openrct2 <other arguments to openrct2>
(gdb) r
# wait for the crash
(gdb) bt
```
Don't post screenshots of text

**Comment by telk5093** [comment]
Here is the result with taking screenshot of [2.zip](https://github.com/OpenRCT2/OpenRCT2/files/5749646/2.zip)

```
telk@ubuntu:/home/orct$ gdb --args ./openrct2-cli screenshot 2.sv6 2.png giant 3 0
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./openrct2-cli...done.
(gdb) run
Starting program: /home/orct/openrct2-cli screenshot 2.sv6 2.png giant 3 0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Object conflict: '/home/telk/.config/OpenRCT2/object/1KMTECWL-02.DAT'
               : '/home/telk/.config/OpenRCT2/object/1KMTECWL.DAT'
Object conflict: '/home/telk/.config/OpenRCT2/object/1KMTECWR-02.DAT'
               : '/home/telk/.config/OpenRCT2/object/1KMTECWR.DAT'
(...)
Object conflict: '/home/orct/data/object/official/ride/rct2.dlc.zpanda.parkobj'
               : '/home/telk/.config/OpenRCT2/object/ZPANDA.DAT'
87 object conflicts found.

Program received signal SIGSEGV, Segmentation fault.
DrawBMPSpriteMinify<1> (args=...) at ../src/openrct2/drawing/Drawing.Sprite.BMP.cpp:58
58      ../src/openrct2/drawing/Drawing.Sprite.BMP.cpp: No such file or directory.
(gdb) bt
#0  DrawBMPSpriteMinify<1> (args=...) at ../src/openrct2/drawing/Drawing.Sprite.BMP.cpp:58
#1  DrawBMPSprite<1> (args=...) at ../src/openrct2/drawing/Drawing.Sprite.BMP.cpp:73
#2  gfx_bmp_sprite_to_buffer (args=...) at ../src/openrct2/drawing/Drawing.Sprite.BMP.cpp:116
#3  0x00007ffff67f60de in gfx_sprite_to_buffer (args=...) at ../src/openrct2/drawing/Drawing.Sprite.cpp:588
#4  0x00007ffff67f6613 in gfx_draw_sprite_palette_set_software (dpi=dpi@entry=0x7fffffffe088, imageId=..., imageId@entry=..., coords=..., paletteMap=...)
    at ../src/openrct2/drawing/Drawing.Sprite.cpp:577
#5  0x00007ffff67f67bb in gfx_draw_sprite_software (dpi=dpi@entry=0x7fffffffe088, imageId=..., imageId@entry=..., spriteCoords=...)
    at ../src/openrct2/drawing/Drawing.Sprite.cpp:413
#6  0x00007ffff67feb35 in scrolling_text_initialise_bitmaps () at ../src/openrct2/drawing/ScrollingText.cpp:81
#7  0x00007ffff67fa6d4 in font_sprite_initialise_characters () at ../src/openrct2/drawing/Font.cpp:266
#8  0x00007ffff678302a in OpenRCT2::Context::LoadBaseGraphics (this=0x555555796d90) at ../src/openrct2/Context.cpp:759
#9  OpenRCT2::Context::Initialise (this=0x555555796d90) at ../src/openrct2/Context.cpp:462
#10 0x00007ffff680b8a2 in cmdline_for_screenshot (argv=0x7fffffffe4f8, argc=5, options=options@entry=0x7ffff6f73f68 <_options>)
    at ../src/openrct2/interface/Screenshot.cpp:635
#11 0x00007ffff67cc4f6 in HandleScreenshot (argEnumerator=<optimized out>) at ../src/openrct2/cmdline/ScreenshotCommands.cpp:46
#12 0x00007ffff67cb624 in cmdline_run (argv=<optimized out>, argc=<optimized out>) at ../src/openrct2/cmdline/CommandLine.cpp:568
#13 0x0000555555554917 in main (argc=7, argv=0x7fffffffe4e8) at ../src/openrct2-cli/Cli.cpp:23
(gdb)
```

**Comment by telk5093** [comment]
No more such issue in the latest build(c5871b4) so I will close this.
