### ISSUE TITLE
Setting Gigacoster to block sectioned, with lift hill, causing immediate crash

### ISSUE THREAD

**Issue by Enzemo** [OpenRCT2/OpenRCT2#1411]
Hey,

So as the title says, when I switch the Gigacoster to block sectioned it's causing the game to crash immediately.

You can repeat this using a save file that I made when I was messing with a sandbox map. Here: 
![autobot](https://cloud.githubusercontent.com/assets/11069930/8269895/a8a58f8a-17b7-11e5-800a-3a8e1a32f23f.png). Save, rename from .png to .sv6

Not sure if it's something else causing it. I'm using the RCT traffic lights and @PFCKrutonium's launcher, so I'm pretty sure I'm on the latest build.

Thanks

edit: forgot to mention, you have to test the ride to make it crash

**Comment by IntelOrca** [comment]
The game gets stuck in a loop (between 0x6DE00C and 0x6DE09A) in sub_6DD84C... the function for creating the vehicles when you open a ride.

Not sure what the issue is, hard to determine as the function is still original code.

**Comment by Enzemo** [comment]
That's cool, I know to avoid it for now.

Thanks for identifying the cause of the issue, sorry I can't offer much help in terms of fixing it. I try to report bugs as much as possible to make up for my lack of coding knowledge ;)

**Comment by duncanspumpkin** [comment]
Original bug, related to #1122 i expect.

**Comment by janisozaur** [comment]
This is decompiled now and issue is still present in 755485f.

A backtrace when loop has been entered:
```
#0  0x0151f322 in invalidate_sprite_max_zoom (sprite=sprite@entry=0x1103fbc, maxZoom=maxZoom@entry=2) at /home/janisozaur/workspace/OpenRCT2/src/world/sprite.c:47
#1  0x0151f47e in invalidate_sprite_2 (sprite=0x1103fbc) at /home/janisozaur/workspace/OpenRCT2/src/world/sprite.c:84
#2  0x01761d13 in vehicle_update_track_motion (vehicle=<optimized out>, outStation=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/ride/vehicle.c:8101
#3  0x016b82e9 in loc_6DDF9C (ride=0x13640b8, mapElement=0xfae770) at /home/janisozaur/workspace/OpenRCT2/src/ride/ride.c:4839
#4  0x016cdf34 in ride_create_vehicles (ride=<optimized out>, rideIndex=<optimized out>, element=<optimized out>, isApplying=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/ride/ride.c:4786
#5  0x016ce88a in ride_is_valid_for_test (rideIndex=<optimized out>, goingToBeOpen=<optimized out>, isApplying=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/ride/ride.c:5250
#6  0x016d02b4 in game_command_set_ride_status (eax=<optimized out>, ebx=<optimized out>, ecx=<optimized out>, edx=<optimized out>, esi=<optimized out>, edi=<optimized out>, ebp=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/ride/ride.c:5478
#7  0x01433388 in game_do_command_p (command=<optimized out>, eax=<optimized out>, ebx=<optimized out>, ecx=<optimized out>, edx=<optimized out>, esi=<optimized out>, edi=<optimized out>, ebp=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/game.c:516
#8  0x014342ff in game_do_command (eax=<optimized out>, ebx=<optimized out>, ecx=<optimized out>, edx=<optimized out>, esi=<optimized out>, edi=<optimized out>, ebp=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/game.c:432
#9  0x016ba46d in ride_set_status (rideIndex=10, status=2) at /home/janisozaur/workspace/OpenRCT2/src/ride/ride.c:5400
#10 0x014a801c in input_state_widget_pressed (x=298, y=85, state=2, widgetIndex=18, w=0x1ed4a60 <g_window_list+1216>, widget=0x1bd0f60 <window_ride_main_widgets+288>) at /home/janisozaur/workspace/OpenRCT2/src/input.c:1271
#11 0x014a973a in game_handle_input_mouse (x=x@entry=298, y=<optimized out>, state=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/input.c:362
#12 0x014ae86f in game_handle_input () at /home/janisozaur/workspace/OpenRCT2/src/input.c:151
#13 0x01432ceb in game_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:343
#14 0x014ba21b in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:463
#15 0x01820786 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:391
#16 openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:321
#17 0x0142e20c in main (argc=2, argv=0xffffd694) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60
```

**Comment by janisozaur** [comment]
Doesn't seem to happen anymore as of 418eb06
