### ISSUE TITLE
Crash when loading on android 11

### ISSUE THREAD

**Issue by cfe316** [OpenRCT2/OpenRCT2#17560]
### Operating System

Android 11 - lineage OS

### OpenRCT2 build

Android ARM undefined	OpenRCT2-0.4.1-android-arm.apk, checksum ac77705

### Describe the issue

I'm running the most recent Lineage OS 18.1 (Android 11) on my LG V20.
I've downloaded the "Latest v0.4.1" android APK build with checksum ac77705; it seems to have successfully installed.

I've copied my desktop installation's `openrct2` and `rct2` directories to the `/storage/emulated/0` directory and configured `config.ini` to point to those paths.

When I tap on the app to open it, the screen goes black. About 3 seconds later, the loading screen music (one of the Merry-Go-Round songs?) starts playing. A few seconds later it crashes. I've tried this about 8 times. Once I saw a normal-looking main menu screen for a fraction of a second before it crashed.

I tried observing using `adb logcat` and saw these errors (in attachments) as part of the stream.

I do see that about  a dozen files have been created by the app in the `/storage/emulated/0/openrct2-user` folder.

### Steps to reproduce

1. Install OpenRCT2 apk
2. copied necessary files and config.ini
3. Touch the app icon to start.

### Attachments

```
07-16 14:26:49.055  2876  6126 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.openrct2/.MainActivity bnds=[40,181][312,568]} from uid 10169
07-16 14:26:49.066   650   650 D QCOM PowerHAL: LAUNCH HINT: ON
07-16 14:26:49.069   650   650 D QCOM PowerHAL: Activity launch hint handled
07-16 14:26:49.085  2876  3755 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (5496034)
07-16 14:26:49.158 11780 11780 E OpenRCT2: Error extracting files
07-16 14:26:49.158 11780 11780 E OpenRCT2: java.io.FileNotFoundException: openrct2
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.content.res.AssetManager.nativeOpenAsset(Native Method)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.content.res.AssetManager.open(AssetManager.java:876)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.content.res.AssetManager.open(AssetManager.java:853)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at io.openrct2.MainActivity.copyAsset(MainActivity.java:147)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at io.openrct2.MainActivity.copyAssets(MainActivity.java:133)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at io.openrct2.MainActivity.startGame(MainActivity.java:116)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at io.openrct2.MainActivity.onStart(MainActivity.java:99)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.Activity.performStart(Activity.java:8018)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3457)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.os.Handler.dispatchMessage(Handler.java:106)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.os.Looper.loop(Looper.java:223)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at android.app.ActivityThread.main(ActivityThread.java:7664)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at java.lang.reflect.Method.invoke(Native Method)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
07-16 14:26:49.158 11780 11780 E OpenRCT2:      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
07-16 14:26:49.159  2876  6126 I ActivityTaskManager: START u0 {cmp=io.openrct2/.GameActivity} from uid 10186
07-16 14:26:49.162   650   650 D QCOM PowerHAL: LAUNCH HINT: ON
```

**Comment by cfe316** [comment]
I tried reinstalling the app and it successfully went to the loading screen the first time, but then after quitting (using the quit button) and restarting the app, it crashed again before reaching the loading screen.

**Comment by cfe316** [comment]
Ok, it looks like the error is around Line 134 of `OpenRCT2/src/openrct2-android/app/src/main/java/io/openrct2/MainActivity.java`

```
    // TODO Don't copy/enumerate assets on every startup
    // When building, ensure OpenRCT2 assets are inside their own directory within the APK assets,
    // so that we do not attempt to copy files out of the standard Android asset folders - webkit, etc.
    private void copyAssets() {
        File dataDir = new File(Environment.getExternalStorageDirectory().toString()
            + File.separator + "openrct2" + File.separator);

        try {
            copyAsset(getAssets(), "openrct2", dataDir, "");
        } catch (IOException e) {
            Log.e(TAG, "Error extracting files", e);
            return;
        }

        assetsCopied = true;
    }

    // srcPath cannot be the empty string
    private void copyAsset(AssetManager assets, String srcPath, File dataDir, String destPath) throws IOException {
        String[] list = assets.list(srcPath);

        if (list.length == 0) {
            InputStream input = assets.open(srcPath);
            File extractedFile = new File(dataDir, destPath);
            File parentFile = extractedFile.getParentFile();
            if (!parentFile.exists()) {
                boolean success = parentFile.mkdirs();
                if (!success) {
                    Log.d(TAG, String.format("Error creating folder '%s'", parentFile));
                }
            }
            FileOutputStream output = new FileOutputStream(extractedFile);
            IOUtils.copyLarge(input, output);
            output.close();
            input.close();
            return;
        }

        for (String fileName : list) {
            // This ternary expression makes sure that this string does not begin with a slash
            String destination = destPath + (destPath.equals("") ? "" : File.separator) + fileName;
            copyAsset(assets, srcPath + File.separator + fileName, dataDir, destination);
        }
    }
```

I'm not a Java programmer, so it'll take me a bit to unpack what's going wrong here.

**Comment by cfe316** [comment]
This seems to be the same issue as  #12576.

**Comment by xmusjackson** [comment]
I haven't tried debugging yet as I just installed the app and tested today, but on LineageOS 18.1 on the LG G8 I also get a black screen followed shortly by a crash after quitting the app. I first attempted clearing the cache and after that worked I took it one step backward and only force stopped the app, which appears to work without reinstalling the app.

**Comment by jsoberg** [comment]
Taking a quick look at the code (and the described devices), I'm wondering if this is giving you the wrong directory - `Environment.getExternalStorageDirectory()` could potentially be returning the SD card location vs expected internal storage (or vice versa), even if it's not mounted (as far as I can remember, at least)

Also not quite sure if  `Environment.getExternalStorageDirectory().toString()` will return the path in every case - `Environment.getExternalStorageDirectory().getAbsolutePath()` would most likely be what you're looking for instead

**Comment by janisozaur** [comment]
Is this still valid?

**Comment by cfe316** [comment]
Hey, thanks for checking in. I haven't played around with Android for a while, and don't anticipate doing it again in the near future. Feel free to close the issue.
