### ISSUE TITLE
`benchspritesort` is not working since #10664

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#19891]
### Operating System

linux

### OpenRCT2 build

0.4.4

### Base game

RollerCoaster Tycoon 2

### Describe the issue

`benchspritesort` stopped working with https://github.com/OpenRCT2/OpenRCT2/pull/10664

### Steps to reproduce

`./openrct2 benchspritesort ~/.config/OpenRCT2/save/Amity\ Airfieldaallasd.sv6`
```
>>> bt
#0  0x0000555555a072b1 in viewport_paint (viewport=0x7fffffffd680, dpi=0x7fffffffd6b0, screenRect=..., recorded_sessions=0x7fffffffd660) at /home/mijn/workspace/openrct2/src/openrct2/interface/Viewport.cpp:999
#1  0x0000555555a067ac in viewport_render (dpi=0x7fffffffd6b0, viewport=0x7fffffffd680, screenRect=..., sessions=0x7fffffffd660) at /home/mijn/workspace/openrct2/src/openrct2/interface/Viewport.cpp:827
#2  0x0000555555fbb7eb in extract_paint_session (parkFileName="/home/mijn/.config/OpenRCT2/save/Amity Airfieldaallasd.sv6") at /home/mijn/workspace/openrct2/src/openrct2/cmdline/BenchSpriteSort.cpp:129
#3  0x0000555555fbc038 in cmdline_for_bench_sprite_sort (argc=1, argv=0x7fffffffda68) at /home/mijn/workspace/openrct2/src/openrct2/cmdline/BenchSpriteSort.cpp:189
#4  0x0000555555fbc284 in HandleBenchSpriteSort (argEnumerator=0x7fffffffd880) at /home/mijn/workspace/openrct2/src/openrct2/cmdline/BenchSpriteSort.cpp:211
#5  0x0000555555967361 in cmdline_run (argv=0x7fffffffda58, argc=3) at /home/mijn/workspace/openrct2/src/openrct2/cmdline/CommandLine.cpp:555
#6  0x0000555555621f1c in main (argc=3, argv=0x7fffffffda58) at /home/mijn/workspace/openrct2/src/openrct2-ui/Ui.cpp:44
>>> p *dpi
$1 = {
  bits = 0x55555b863b60 "\020dQZUU",
  x = 0,
  y = 0,
  width = 7048,
  height = 3648,
  pitch = 0,
  zoom_level = {
    _level = 0 '\000'
  },
  remX = 0 '\000',
  remY = 0 '\000',
  lastStringPos = {
    x = 0,
    y = 0
  },
  DrawingEngine = 0x0
}
```
https://github.com/OpenRCT2/OpenRCT2/blob/34128dc262cefd38911b7833ecc2ec5ea40dee69/src/openrct2/interface/Viewport.cpp#L999

**Comment by ZehMatt** [comment]
A lot of code around the paint struct stuff is broken and been meaning to actually rip it out and also move all the benchmarking into a separate project, I'm actually waiting for us to move to cmake so we can just maintain a single thing for when we refactor the project structure.

**Comment by 733737** [comment]
I am unable to build the game using msbuild now because of benchspritesort

**Comment by spacek531** [comment]
what error do you get? @733737

**Comment by 733737** [comment]
I will screenshot the output of cmd when I get home. I am still at work atm

**Comment by janisozaur** [comment]
please don't screenshot it. It's text and leave it as text

**Comment by 733737** [comment]
apparently it was just an issue with my git data folder. I fixed the issue now
