### ISSUE TITLE
Dynamite Dunes instant crash on reaching level target

### ISSUE THREAD

**Issue by carlu93** [OpenRCT2/OpenRCT2#2825]
![crash](https://cloud.githubusercontent.com/assets/16781908/12614007/85456c60-c4fd-11e5-9476-96432810c4d2.jpg)
[Dynamite Dunes.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/106588/Dynamite.Dunes.sv6.txt)
I'm attaching the savegame. Maybe you'll find something. As soon as I reach Year 4. The you have won window comes up and the game instantly crashes after that. Build number is: 0.0.4 build 6ee91c7

**Comment by janisozaur** [comment]
any logs?

**Comment by carlu93** [comment]
![window](https://cloud.githubusercontent.com/assets/16781908/12614124/36dd3778-c4fe-11e5-9662-59a506787847.JPG)
nothin ' happening over here or is there a logfile?

**Comment by janisozaur** [comment]
That's a nice repro.
```
#0  0x014bdb5b in steam_particle_create (x=2992, y=2556, z=123) at /work/OpenRCT2/src/ride/vehicle.c:6055
#1  0x014bdd31 in sub_6D63D4 (vehicle=0x10f4bbc) at /work/OpenRCT2/src/ride/vehicle.c:6100
#2  0x014c2675 in vehicle_update_track_motion (vehicle=0x10f4bbc, outStation=0x0) at /work/OpenRCT2/src/ride/vehicle.c:8023
#3  0x014b7e4d in vehicle_update_travelling (vehicle=0x10f4bbc) at /work/OpenRCT2/src/ride/vehicle.c:2615
#4  0x014b4e8c in vehicle_update (vehicle=0x10f4bbc) at /work/OpenRCT2/src/ride/vehicle.c:1161
#5  0x014b38d5 in vehicle_update_all () at /work/OpenRCT2/src/ride/vehicle.c:576
#6  0x0153df6d in game_logic_update () at /work/OpenRCT2/src/game.c:370
#7  0x0153dd5e in game_update () at /work/OpenRCT2/src/game.c:286
#8  0x0153d1ee in rct2_update () at /work/OpenRCT2/src/rct2.c:455
#9  0x014acd17 in openrct2_loop () at /work/OpenRCT2/src/openrct2.c:454
#10 0x014ac76e in openrct2_launch () at /work/OpenRCT2/src/openrct2.c:321
#11 0x01503d17 in main (argc=2, argv=0xffffd434) at /work/OpenRCT2/src/platform/posix.c:64
```
