### ISSUE TITLE
Crash in native code 0x00993e1c

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#3293]
**OS:** Windows 
**Version:** 0.0.4-develop
**Commit:** 2090c4aa

Crash in native code, dump included.

Open saved game, zoom out, should crash.

- [x] Multiplayer?

**Dump file**
[OpenRCT2-dump-2090c4aa.zip](https://github.com/OpenRCT2/OpenRCT2/files/216110/OpenRCT2-dump-2090c4aa.zip)

[openrct2-symbols-2090c4a.zip](https://github.com/OpenRCT2/OpenRCT2/files/216126/openrct2-symbols-2090c4a.zip)

[openrct2-2090c4a.zip](https://github.com/OpenRCT2/OpenRCT2/files/216133/openrct2-2090c4a.zip)

**Comment by janisozaur** [comment]
```
#0  RCT2_CALLPROC_X (address=6841552, _eax=65280, _ebx=3123, _ecx=1280, _edx=16, _esi=32, _edi=32, _ebp=2) at /home/janisozaur/workspace/OpenRCT2/src/addresses.c:35
#1  0x01525004 in viewport_blank_tiles_paint_setup (x=0, y=1280) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:1948
#2  0x01525200 in map_element_paint_setup (x=-32, y=1248) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:2020
#3  0x01525506 in viewport_paint_setup () at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:2094
#4  0x015260b7 in viewport_paint (viewport=0x14234bc, dpi=0xffffcf94, left=64284, top=64907, right=-924, bottom=-529) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:2401
#5  0x01522567 in viewport_render (dpi=0xffffcf94, viewport=0x14234bc, left=-1252, top=-629, right=-924, bottom=-529) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:735
#6  0x014986e4 in window_main_paint (w=0x1420078, dpi=0xffffcf94) at /home/janisozaur/workspace/OpenRCT2/src/windows/main.c:101
#7  0x0152b202 in window_event_paint_call (w=0x1420078, dpi=0xffffcf94) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:2018
#8  0x0152a3de in window_draw (w=0x1420078, left=527, top=676, right=855, bottom=776) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1584
#9  0x0153b417 in gfx_redraw_screen_rect (left=527, top=676, right=855, bottom=776) at /home/janisozaur/workspace/OpenRCT2/src/drawing/drawing.c:347
#10 0x01521a59 in sub_6E7F34 (w=0x1420538, viewport=0x14234bc, x_diff=1088, y_diff=4991) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:472
#11 0x01521e93 in sub_6E7DE1 (x=-1779, y=-1305, w=0x1420078, viewport=0x14234bc) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:546
#12 0x015222b8 in viewport_update_position (window=0x1420078) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:674
#13 0x0144fec3 in title_set_location (x=240, y=1328) at /home/janisozaur/workspace/OpenRCT2/src/title.c:242
#14 0x0145015b in title_do_next_script_opcode () at /home/janisozaur/workspace/OpenRCT2/src/title.c:338
#15 0x01450657 in title_update_showcase () at /home/janisozaur/workspace/OpenRCT2/src/title.c:472
#16 0x014513b4 in title_refresh_sequence () at /home/janisozaur/workspace/OpenRCT2/src/title.c:790
#17 0x0144fbff in title_init_showcase () at /home/janisozaur/workspace/OpenRCT2/src/title.c:171
#18 0x0144fb6f in title_load () at /home/janisozaur/workspace/OpenRCT2/src/title.c:135
#19 0x01453c43 in rct2_init () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:187
#20 0x01544dec in openrct2_initialise () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:241
#21 0x01544e9b in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:269
#22 0x015415b9 in main (argc=2, argv=0xffffd634) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:64
```

**Comment by IntelOrca** [comment]
I can't load this saved game, missing objects.

**Comment by janisozaur** [comment]
[0a5c9f6f-0823-4d82-8c88-a184527203f5.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/219623/0a5c9f6f-0823-4d82-8c88-a184527203f5.sv6.zip)

this should give you the objects, but the save can be different than the on from the dump.

**Comment by IntelOrca** [comment]
This is again another invalid track element.
