### ISSUE TITLE
New Crash #2

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3434]
**OS:** Win 7 64 Bit
**Version:** 0.0.5 develop
**Build ID:** 45843ec

This server crashed upon entry

[April26crash2.zip](https://github.com/OpenRCT2/OpenRCT2/files/237803/April26crash2.zip)

**Comment by janisozaur** [comment]
Save game reproduces the crash. Tested on 82dd760

```
>>> p mapElement 
$1 = (rct_map_element *) 0x0
>>> bt
#0  0x0181988f in ride_update_station_blocksection (ride=0x1364ef8, stationIndex=1) at /home/janisozaur/workspace/OpenRCT2/src/ride/station.c:69
#1  0x01819592 in ride_update_station (ride=0x1364ef8, stationIndex=1) at /home/janisozaur/workspace/OpenRCT2/src/ride/station.c:48
#2  0x0175c13a in ride_update (rideIndex=16) at /home/janisozaur/workspace/OpenRCT2/src/ride/ride.c:1929
#3  0x0175bf99 in ride_update_all () at /home/janisozaur/workspace/OpenRCT2/src/ride/ride.c:1907
#4  0x0142dfb8 in game_logic_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:373
#5  0x0142d926 in game_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:287
#6  0x014ebc83 in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:458
#7  0x0198b866 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:392
#8  0x0198b253 in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:322
#9  0x0197f5a3 in main (argc=2, argv=0xffffd6c4) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60
```
