### ISSUE TITLE
Multiplayer Crash

### ISSUE THREAD

**Issue by Superjustinbros** [OpenRCT2/OpenRCT2#3578]
Build ID is c7c3923
[Crash May 12.zip](https://github.com/OpenRCT2/OpenRCT2/files/261907/Crash.May.12.zip)

**Comment by janisozaur** [comment]
Can you provide following objects:
* `TRACK2`
* `TRACK22`
* `RRPOLE`
* `RRTUNN`
* `PATHGLA`

**Comment by Superjustinbros** [comment]
[rct2pa.zip](https://github.com/OpenRCT2/OpenRCT2/files/263376/rct2pa.zip)

**Comment by janisozaur** [comment]
Save game can reproduce a crash, when you open it, just scroll the map towards upper-right part.

```
#0  RCT2_CALLPROC_X (address=0x006C4934, _eax=22, _ebx=1711316453, _ecx=1, _edx=112, _esi=16816360, _edi=83904, _ebp=3) at /home/janisozaur/workspace/OpenRCT2/src/addresses.c:31
#1  0x014946ea in track_paint (direction=<optimized out>, height=<optimized out>, mapElement=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/ride/track_paint.c:124
#2  0x014f2753 in sub_68B3FB (x=<optimized out>, y=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/map_element.c:249
#3  0x014f2a0f in map_element_paint_setup (x=<optimized out>, y=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/paint/map_element/map_element.c:64
#4  0x014f74ea in viewport_paint_setup () at /home/janisozaur/workspace/OpenRCT2/src/paint/paint.c:638
#5  0x0147d6bc in viewport_paint (viewport=0x164a760 <g_viewport_list>, dpi=0xffcc9680, left=<optimized out>, top=<optimized out>, right=<optimized out>, bottom=<optimized out>)
    at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:789
#6  0x0147d81a in viewport_render (dpi=<optimized out>, viewport=<optimized out>, left=<optimized out>, top=<optimized out>, right=<optimized out>, bottom=<optimized out>)
    at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:691
#7  0x014364ad in window_main_paint (w=0x164ac80 <g_window_list>, dpi=0xffcc9680) at /home/janisozaur/workspace/OpenRCT2/src/windows/main.c:98
#8  0x01481230 in window_event_paint_call (dpi=0xffcc9680, w=0x164ac80 <g_window_list>) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:2011
#9  window_draw (w=<optimized out>, left=0, top=<optimized out>, right=1169, bottom=<optimized out>) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1580
#10 0x014be78c in gfx_redraw_screen_rect (left=0, top=0, right=1169, bottom=28) at /home/janisozaur/workspace/OpenRCT2/src/drawing/drawing.c:359
#11 0x0147d0a7 in sub_6E7F34 (w=0x164b140 <g_window_list+1216>, viewport=0x164a760 <g_viewport_list>, x_diff=-22, y_diff=10)
    at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:426
#12 0x0147d1fe in sub_6E7DE1 (x=4002, y=4854, w=0x164ac80 <g_window_list>, viewport=0x164a760 <g_viewport_list>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:500
#13 0x0147dc45 in viewport_update_position (window=0x164ac80 <g_window_list>) at /home/janisozaur/workspace/OpenRCT2/src/interface/viewport.c:628
#14 0x0147ec88 in window_update_all_viewports () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:160
#15 0x01480c88 in window_update_all () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:174
#16 0x01507c9f in rct2_draw () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:280
#17 0x014fd00f in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:420
#18 openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:321
#19 0x01429286 in main (argc=2, argv=0xffcc9984) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60
```

**Comment by Nubbie** [comment]
_Crash tag_

**Comment by janisozaur** [comment]
Crash was in native code, doesn't happen anymore.
