### ISSUE TITLE
Inspecting sidewalk path crashes game

### ISSUE THREAD

**Issue by jensj12** [OpenRCT2/OpenRCT2#3635]
**OS:** win10
**Version:** 0.0.5 develop
**Commit:** eb19ca8

The tile inspector crashes as soon as I click a tile with a sidewalk path when the queue line TV object is not selected.

Edit: In the test park turning the Queue Line TV on in the object selection fixes it, though in other scenario's it's another object (as far as I've tested always from the footpath extras tab)

**Steps to reproduce:**
1. Open the save included in the zip (or any other save WITH the sidewalk footpath enabled and WITHOUT queue line TV's enabled)
2. Open the tile inspector
3. Click on a tile with the sidewalk footpath
4. Crash (if TV's are enabled, it will show 'Path (Queue Line TV)')

**Dump file + save**
[OpenRCT2crashes4.zip](https://github.com/OpenRCT2/OpenRCT2/files/266696/OpenRCT2crashes4.zip)

**Comment by janisozaur** [comment]
```
#0  0x015b2abd in window_tile_inspector_scrollpaint (w=0x23db720 <g_window_list+1216>, dpi=0xffffcd00, scrollIndex=0) at /home/janisozaur/workspace/OpenRCT2/src/windows/tile_inspector.c:613
#1  0x016359c6 in window_event_scroll_paint_call (w=0x23db720 <g_window_list+1216>, dpi=0xffffcd00, scrollIndex=0) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1980
#2  0x0165f13c in widget_scroll_draw (dpi=0xffffd020, w=0x23db720 <g_window_list+1216>, widgetIndex=3) at /home/janisozaur/workspace/OpenRCT2/src/interface/widget.c:776
#3  0x0165508f in widget_draw (dpi=0xffffd020, w=0x23db720 <g_window_list+1216>, widgetIndex=3) at /home/janisozaur/workspace/OpenRCT2/src/interface/widget.c:151
#4  0x016303e3 in window_draw_widgets (w=0x23db720 <g_window_list+1216>, dpi=0xffffd020) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1614
#5  0x015afbd6 in window_tile_inspector_paint (w=0x23db720 <g_window_list+1216>, dpi=0xffffd020) at /home/janisozaur/workspace/OpenRCT2/src/windows/tile_inspector.c:509
#6  0x0163580a in window_event_paint_call (w=0x23db720 <g_window_list+1216>, dpi=0xffffd020) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1974
#7  0x0162ebe7 in window_draw (w=0x23db260 <g_window_list>, left=0, top=64, right=512, bottom=256) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1543
#8  0x017d46de in gfx_redraw_screen_rect (left=0, top=64, right=512, bottom=256) at /home/janisozaur/workspace/OpenRCT2/src/drawing/drawing.c:355
#9  0x017d3d38 in gfx_draw_dirty_blocks (x=0, y=1, columns=4, rows=3) at /home/janisozaur/workspace/OpenRCT2/src/drawing/drawing.c:325
#10 0x017d3ad2 in gfx_draw_all_dirty_blocks () at /home/janisozaur/workspace/OpenRCT2/src/drawing/drawing.c:296
#11 0x0161fb0d in window_update_all () at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:160
#12 0x0194cf0f in rct2_draw () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:284
#13 0x0195a0a7 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:421
#14 0x01958e3f in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:322
#15 0x017f9037 in main (argc=2, argv=0xffffd334) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60
```
