### ISSUE TITLE
Game crash if the syntax of "users.json" file is wong

### ISSUE THREAD

**Issue by telk5093** [OpenRCT2/OpenRCT2#4295]
**OS:** Windows 10
**Version:** 0.0.5
**Commit/Build:** b9a4ef8

If syntax of users.json file is wrong, then it is unable to open server and the game crashes.

- [ ] Reproducible in RCT2 (vanilla)?
- [x] Multiplayer?

**Steps to reproduce:**
If _users.json_ file looks like below, (Notice that there is no comma after first }.)
```
[
    {
        "hash": "(some hash)",
        "name": "(some name)",
        "groupId": 3
    }
    {
        "hash": "(some hash)",
        "name": "(some name)",
        "groupId": 3
    }
]
```
Then game crashes if I try to open a multiplay server.
Do you think it is possible to make game auto-fix it?

**Comment by IntelOrca** [comment]
I can't reproduce this, I just get
```
ERROR[src\network\network.cpp:873 (Network::LoadGroups)]: Failed to read C:\Users\Ted\Documents\OpenRCT2\groups.json as JSON. Setting default groups. ']' expected near '{'
Ready for clients...
```

server runs as normal, no crash.

Could you send a crash dump?

> Do you think it is possible to make game auto-fix it?

**Comment by telk5093** [comment]
![image](https://cloud.githubusercontent.com/assets/10726524/17708236/1140b844-641f-11e6-9510-d7a502135ea0.png)
[b56ce5c6-3ab8-4bfc-b6c8-5e9c88fa5b96(b9a4ef8).zip](https://github.com/OpenRCT2/OpenRCT2/files/420843/b56ce5c6-3ab8-4bfc-b6c8-5e9c88fa5b96.b9a4ef8.zip)
Here it is.
And this is the users.json file what I used when I reproduce this issue in my circumstance:
```
[
    {
        "hash": "3e4a1b91b8d6c097eff661fe2a5f7dc68760d8fc",
        "name": "YJSoft",
        "groupId": 1
    },
    {
        "hash": "89e59331a43a9231f97daca9a5b5cefc1448fa29",
        "name": "Azoshi",
        "groupId": 2
    }
    {
        "hash": "6958b8099a16b21ea5bc7e9a44b1f65c1e8ba8c6",
        "name": "TELK(서버)",
        "groupId": 0
    }
]
```

**Comment by IntelOrca** [comment]
The stack trace is incomplete so I can't work out where this is failing. I tried that file as well and still can't reproduce.

**Comment by janisozaur** [comment]
```
terminate called after throwing an instance of 'JsonException'
  what():  ']' expected near '{'
```

```
#7  0x0157b6c2 in Json::ReadFromFile (path=0xffffce48 "/home/janisozaur/.config/OpenRCT2/users.json", maxSize=67108864) at /home/janisozaur/workspace/OpenRCT2/src/core/Json.cpp:45
#8  0x015a3b08 in NetworkUserManager::Load (this=0x17dd88c <gNetwork+44>) at /home/janisozaur/workspace/OpenRCT2/src/network/NetworkUser.cpp:97
#9  0x015a9e97 in Network::BeginServer (this=0x17dd860 <gNetwork>, port=11753, address=0x0) at /home/janisozaur/workspace/OpenRCT2/src/network/network.cpp:284
#10 0x015b12b4 in network_begin_server (port=11753) at /home/janisozaur/workspace/OpenRCT2/src/network/network.cpp:1987
#11 0x01541aaa in window_server_start_scenarioselect_callback (path=0x19cb6c8 "/home/janisozaur/games/rct2/Scenarios/Factory Capers.SC6") at /home/janisozaur/workspace/OpenRCT2/src/windows/server_start.c:156
#12 0x0154f15a in window_scenarioselect_scrollmousedown (w=0x17e2658 <g_window_list+8568>, scrollIndex=0, x=340, y=-13) at /home/janisozaur/workspace/OpenRCT2/src/windows/title_scenarioselect.c:290
#13 0x01450337 in window_event_scroll_mousedown_call (w=0x17e2658 <g_window_list+8568>, scrollIndex=0, x=340, y=77) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1979
#14 0x0143a047 in input_scroll_begin (w=0x17e2658 <g_window_list+8568>, widgetIndex=12, x=632, y=360) at /home/janisozaur/workspace/OpenRCT2/src/input.c:606
#15 0x0143b206 in input_widget_left (x=632, y=360, w=0x17e2658 <g_window_list+8568>, widgetIndex=12) at /home/janisozaur/workspace/OpenRCT2/src/input.c:1031
#16 0x014397a5 in game_handle_input_mouse (x=632, y=360, state=1) at /home/janisozaur/workspace/OpenRCT2/src/input.c:316
#17 0x014391fc in game_handle_input () at /home/janisozaur/workspace/OpenRCT2/src/input.c:151
#18 0x014f56e5 in title_update () at /home/janisozaur/workspace/OpenRCT2/src/title.c:543
#19 0x0148ac0a in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:456
#20 0x014596ee in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:415
#21 0x0145950a in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:337
#22 0x01485c9d in main (argc=1, argv=0xffffd344) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:60
```

**Comment by IntelOrca** [comment]
Oh, I was testing groups.json, not users.json...
