### ISSUE TITLE
Crash in research_rides_setup

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4388]
**OS:** Linux
**Commit/Build:** 91eb332

Open attached park, try opening `inventions list` from debug tools menu.

```
#0  0x0150ddfe in research_rides_setup () at /home/janisozaur/workspace/OpenRCT2/src/windows/editor_inventions_list.c:211
        ride_base_type = 30 '\036'
        object_index = 89 'Y'
        ride_entry = 0xffffffff
        master_found = 0 '\000'
        research = 0x18392fe <gResearchItems+30>
#1  0x0150e049 in research_always_researched_setup () at /home/janisozaur/workspace/OpenRCT2/src/windows/editor_inventions_list.c:292
#2  0x0150e695 in window_editor_inventions_list_open () at /home/janisozaur/workspace/OpenRCT2/src/windows/editor_inventions_list.c:543
#3  0x0156e043 in top_toolbar_debug_menu_dropdown (dropdownIndex=3) at /home/janisozaur/workspace/OpenRCT2/src/windows/top_toolbar.c:2999
#4  0x01569155 in window_top_toolbar_dropdown (w=0x18205a8 <g_window_list+1224>, widgetIndex=19, dropdownIndex=3) at /home/janisozaur/workspace/OpenRCT2/src/windows/top_toolbar.c:617
#5  0x01454614 in window_event_dropdown_call (w=0x18205a8 <g_window_list+1224>, widgetIndex=19, dropdownIndex=3) at /home/janisozaur/workspace/OpenRCT2/src/interface/window.c:1909
#6  0x0143dd54 in input_state_widget_pressed (x=175, y=60, state=2, widgetIndex=0, w=0x1820f38 <g_window_list+3672>, widget=0x17d2d40 <window_dropdown_widgets>) at /home/janisozaur/workspace/OpenRCT2/src/input.c:1253
#7  0x0143b9f9 in game_handle_input_mouse (x=175, y=60, state=2) at /home/janisozaur/workspace/OpenRCT2/src/input.c:349
#8  0x0143b218 in game_handle_input () at /home/janisozaur/workspace/OpenRCT2/src/input.c:134
#9  0x0143847d in game_update () at /home/janisozaur/workspace/OpenRCT2/src/game.c:346
#10 0x01492e97 in rct2_update () at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:457
#11 0x0145ee78 in openrct2_loop () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:415
#12 0x0145ec4e in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:337
#13 0x0148d6d3 in main (argc=2, argv=0xffffd634) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:57
```

Notice: `ride_entry = 0xffffffff`

Also crashes when closing object selection window after trying modifying it, most likely for the same reason.

**Save game:**
[dome-roof-on_zoom1.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/462687/dome-roof-on_zoom1.sv6.zip)

**Comment by IntelOrca** [comment]
You export that save with objects?

**Comment by janisozaur** [comment]
[dome-export.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/463781/dome-export.sv6.zip)

There. It's http://www.nedesigns.com/park/3324/h2h7-r1-circus-circus-adventuredome-atlantic-city/

**Comment by Chaosmeister** [comment]
The crash seems to be prevented already.

That is all I get:
![image](https://user-images.githubusercontent.com/13346344/27997093-3aa6b0de-64f1-11e7-85e6-4659551f47df.png)

**Comment by janisozaur** [comment]
@Chaosmeister you are missing objects, which were attached in my comment above. But indeed, this file is no handled without crashes.
