### ISSUE TITLE
Park with object containing no images fails to load

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#4537]
**OS:** Linux
**Commit/Build:** 001120e

Attached park does not load in x86-64 build.

- [x] Multiplayer? The park was created in multiplayer, connecting to it (when hosted with 32 bit server) does not work either.

```
#3  0x00007ffff34adf52 in __assert_fail () from /usr/lib/libc.so.6
No symbol table info available.
#4  0x0000000000ab9a7b in Guard::Assert_VA (expression=false, message=0xf4f420 "Location: %s:%d", args=0x7fffffffd780) at /home/janisozaur/workspace/OpenRCT2/src/core/Guard.cpp:91
        __PRETTY_FUNCTION__ = "void Guard::Assert_VA(bool, const char*, __va_list_tag*)"
#5  0x0000000000ab99b9 in Guard::Assert (expression=false, message=0xf4f420 "Location: %s:%d") at /home/janisozaur/workspace/OpenRCT2/src/core/Guard.cpp:51
        args = <error reading variable args (Attempt to dereference a generic pointer.)>
#6  0x0000000000ac9a58 in AllocateImageList (count=0) at /home/janisozaur/workspace/OpenRCT2/src/drawing/Image.cpp:151
        __func__ = "AllocateImageList"
        baseImageId = 17144
        freeImagesRemaining = 24800
#7  0x0000000000aca109 in gfx_object_allocate_images (images=0x0, count=0) at /home/janisozaur/workspace/OpenRCT2/src/drawing/Image.cpp:206
        baseImageId = 0
        __func__ = "gfx_object_allocate_images"
        imageId = 32767
#8  0x0000000000c3cb4e in SmallSceneryObject::Load (this=0x60e0000042c0) at /home/janisozaur/workspace/OpenRCT2/src/object/SmallSceneryObject.cpp:84
No locals.
#9  0x0000000000c08e8a in ObjectManager::GetOrLoadObject (this=0x60300002f6b0, ori=0x7fffd7498980) at /home/janisozaur/workspace/OpenRCT2/src/object/ObjectManager.cpp:478
        loadedObject = 0x60e0000042c0
#10 0x0000000000c0870b in ObjectManager::LoadObjects (this=0x60300002f6b0, requiredObjects=0x62200001b100, outNewObjectsLoaded=0x7fffffffda90) at /home/janisozaur/workspace/OpenRCT2/src/object/ObjectManager.cpp:449
        loadedObject = 0x0
        ori = 0x7fffd7498980
        i = 243
        newObjectsLoaded = 242
        loadedObjects = 0x622000019900
#11 0x0000000000c01524 in ObjectManager::LoadObjects (this=0x60300002f6b0, entries=0x7fffc4d929c8, count=721) at /home/janisozaur/workspace/OpenRCT2/src/object/ObjectManager.cpp:124
        numRequiredObjects = 575
        requiredObjects = 0x62200001b100
        numNewLoadedObjects = 140737488345792
        loadedObjects = 0xc0a3f6 <std::_Tuple_impl<0ul, ObjectManager*, std::default_delete<ObjectManager> >::_M_head(std::_Tuple_impl<0ul, ObjectManager*, std::default_delete<ObjectManager> > const&)+62>
#12 0x0000000000c0f66f in object_load_entries (entries=0x7fffc4d929c8) at /home/janisozaur/workspace/OpenRCT2/src/object/ObjectRepository.cpp:719
        objectManger = 0x60300002f6b0
        result = false
#13 0x0000000000c81582 in S6Importer::Import (this=0x7fffc4d92800) at /home/janisozaur/workspace/OpenRCT2/src/rct2/S6Importer.cpp:349
No locals.
#14 0x0000000000c818d5 in game_load_sv6 (rw=0x6070000129a0) at /home/janisozaur/workspace/OpenRCT2/src/rct2/S6Importer.cpp:384
        __func__ = "game_load_sv6"
        result = false
        s6Importer = 0x7fffc4d92800
#15 0x0000000000508c96 in game_load_save (path=0x1e8b680 <gOpenRCT2StartupActionPath> "/home/janisozaur/.config/OpenRCT2/save/whiskey_s2_nogo64_2.sv6") at /home/janisozaur/workspace/OpenRCT2/src/game.c:824
        rw = 0x6070000129a0
        __func__ = "game_load_save"
        extension_type = 6
        result = false
#16 0x000000000067b478 in rct2_open_file (path=0x1e8b680 <gOpenRCT2StartupActionPath> "/home/janisozaur/.config/OpenRCT2/save/whiskey_s2_nogo64_2.sv6") at /home/janisozaur/workspace/OpenRCT2/src/rct2.c:355
        extension = 0x1e8b6bb <gOpenRCT2StartupActionPath+59> "sv6"
#17 0x000000000059b6ca in openrct2_launch () at /home/janisozaur/workspace/OpenRCT2/src/openrct2.c:293
No locals.
#18 0x000000000066cf8b in main (argc=2, argv=0x7fffffffe118) at /home/janisozaur/workspace/OpenRCT2/src/platform/posix.c:57
        run_game = 1
```

**Save game:**
[whiskey_s2_nogo64_2.sv6.zip](https://github.com/OpenRCT2/OpenRCT2/files/512174/whiskey_s2_nogo64_2.sv6.zip)

**Comment by IntelOrca** [comment]
I get this in 32-bit as well.
