### ISSUE TITLE
Crash on park with out of bounds sprite coordinates

### ISSUE THREAD

**Issue by xp4xbox** [OpenRCT2/OpenRCT2#5096]
**OS:** [Windows 7]
**Version:** 0.0.6
**Commit/Build:** [abad7dd]

When I try to open this park, http://www.nedesigns.com/park/1571/six-flags-carolina/, the game gives me this message:
![untitled](https://cloud.githubusercontent.com/assets/24964930/22171377/8923a31a-df5a-11e6-9e80-bd6466ec3a2a.png)

But it works fine when I open in vanilla

**Steps to reproduce:**
1. Download and open the park

**Comment by HaasJona** [comment]
```
(gdb) bt
#0  0x00000000008db39d in reset_sprite_spatial_index () at /home/jh/src/OpenRCT2/src/openrct2/world/sprite.c:163
#1  0x0000000000506656 in game_load_init () at /home/jh/src/OpenRCT2/src/openrct2/game.c:911
#2  0x000000000050649c in game_load_save (path=0x7fffffffd930 "/home/jh/Downloads/park/Six Flags Carolina (CedarPoint6).SV6") at /home/jh/src/OpenRCT2/src/openrct2/game.c:866
#3  0x0000000000506de6 in game_load_save_or_scenario (path=0x7fffffffd930 "/home/jh/Downloads/park/Six Flags Carolina (CedarPoint6).SV6") at /home/jh/src/OpenRCT2/src/openrct2/game.c:1116
#4  0x0000000000506e23 in game_load_or_quit_no_save_prompt_callback (result=1, path=0x7fffffffd930 "/home/jh/Downloads/park/Six Flags Carolina (CedarPoint6).SV6") at /home/jh/src/OpenRCT2/src/openrct2/game.c:1126
#5  0x000000000086f303 in window_loadsave_invoke_callback (result=1, path=0x7fffffffd930 "/home/jh/Downloads/park/Six Flags Carolina (CedarPoint6).SV6") at /home/jh/src/OpenRCT2/src/openrct2/windows/loadsave.c:689
#6  0x000000000086f476 in window_loadsave_select (w=0x111ec20 <g_window_list+6240>, path=0x7fffffffd930 "/home/jh/Downloads/park/Six Flags Carolina (CedarPoint6).SV6") at /home/jh/src/OpenRCT2/src/openrct2/windows/loadsave.c:726
#7  0x000000000086def3 in window_loadsave_mouseup (w=0x111ec20 <g_window_list+6240>, widgetIndex=10) at /home/jh/src/OpenRCT2/src/openrct2/windows/loadsave.c:299
#8  0x000000000051f5b0 in window_event_mouse_up_call (w=0x111ec20 <g_window_list+6240>, widgetIndex=10) at /home/jh/src/OpenRCT2/src/openrct2/interface/window.c:1897
#9  0x0000000000509f15 in input_state_widget_pressed (x=586, y=544, state=2, widgetIndex=10, w=0x111ec20 <g_window_list+6240>, widget=0xd950e0 <window_loadsave_widgets+320>) at /home/jh/src/OpenRCT2/src/openrct2/input.c:1281
#10 0x0000000000507760 in game_handle_input_mouse (x=586, y=544, state=2) at /home/jh/src/OpenRCT2/src/openrct2/input.c:324
#11 0x0000000000507008 in game_handle_input () at /home/jh/src/OpenRCT2/src/openrct2/input.c:134
#12 0x0000000000968ea5 in title_update () at /home/jh/src/OpenRCT2/src/openrct2/title/TitleScreen.cpp:210
#13 0x00000000005622c8 in rct2_update () at /home/jh/src/OpenRCT2/src/openrct2/rct2.c:454
#14 0x00000000008df1f9 in OpenRCT2::RunVariableFrame () at /home/jh/src/OpenRCT2/src/openrct2/OpenRCT2.cpp:493
#15 0x00000000008df022 in OpenRCT2::RunGameLoop () at /home/jh/src/OpenRCT2/src/openrct2/OpenRCT2.cpp:416
#16 0x00000000008deb2e in openrct2_launch () at /home/jh/src/OpenRCT2/src/openrct2/OpenRCT2.cpp:299
#17 0x000000000055d631 in main (argc=1, argv=0x7fffffffddd8) at /home/jh/src/OpenRCT2/src/openrct2/platform/posix.c:59

(gdb) info locals
index = 4294716053
nextSpriteId = 65535
spr = 0xe88860 <_spriteList+256>
i = 1

(gdb) print spr->unknown
$5 = {sprite_identifier = 0 '\000', misc_identifier = 1 '\001', next_in_quadrant = 65535, next = 220, previous = 292, linked_list_type_offset = 10 '\n', sprite_height_negative = 19 '\023', sprite_index = 1, flags = 0, x = -31400, y = 4784, z = 115, sprite_width = 14 '\016', sprite_height_positive = 9 '\t', sprite_left = 26602, sprite_top = -14810, sprite_right = 26630, sprite_bottom = -14782, sprite_direction = 16 '\020', pad_1F = {0 '\000', 0 '\000', 0 '\000'}, name_string_idx = 0, var_24 = 8715, frame = 0, var_28 = {0 '\000', 0 '\000', 0 '\000'}, var_2B = 0 '\000', pad_2C = {0 '\000', 0 '\000', 0 '\000', 0 '\000', 130 '\202', 0 '\000', 6 '\006', 6 '\006', 24 '\030', 0 '\000', 14 '\016', 0 '\000', 64 '@', 133 '\205', 160 '\240', 18 '\022', 112 'p', 0 '\000', 36 '$', 1 '\001', 252 '\374', 0 '\000', 36 '$', 1 '\001', 85 'U', 0 '\000', 44 ',', 1 '\001', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 0 '\000', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377', 255 '\377'}, var_71 = 255 '\377'}
(gdb) print spr->unknown.x
$4 = -31400
```

So `spr->unknown.x` has a weird large negative value which causes the spatial index compitation to fail.

**Comment by xp4xbox** [comment]
But I dont get why it works on vanilla.

**Comment by PFCKrutonium** [comment]
Probably just lucky tbh.

**Comment by janisozaur** [comment]
@xp4xbox that's because vanilla did absolutely no bounds checking and gladly returned 65535th sprite.

**Comment by xp4xbox** [comment]
Is there a way to make the park work?

**Comment by duncanspumpkin** [comment]
@xp4xbox we do strive to support all maps. We will eventually get round to auto fixing this map to correct the issue in the mean time im sure someone could edit the sprite in question to fix it.

**Comment by IntelOrca** [comment]
When it gets the x and y from the sprite, it needs to clamp it to ensure it can't create an invalid spatial index.
