### ISSUE TITLE
Attempting to place TD4 version of Mini Maze results in weird behaviour or crashes

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#5398]
**OS:** Ubuntu 17.04
**Version:** 0.0.7
**Commit/Build:** 34540b64395264851a4ad77c384344438f764d0d

- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Attempt to place Mini maze ([download here](https://files.gitter.im/OpenRCT2/OpenRCT2/1R9T/Mini-Maze.TD4))
2. The game will display "Too high for supports!", "Land not owned by park" or crash outright.

**Debugger output (from the crash)**
```
Starting program: /home/michael/.PlayOnLinux/wineprefix/OpenRCT2/drive_c/Spelletjes/RollerCoaster Tycoon 2/openrct2 
warning: Probes-based dynamic linker interface failed.
Reverting to original interface.

WARNING[/home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/platform/posix.c:807 (platform_get_locale_date_format)]: Function platform_get_locale_date_format at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/platform/posix.c:807 is a stub.

WARNING[/home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/platform/posix.c:807 (platform_get_locale_date_format)]: Function platform_get_locale_date_format at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/platform/posix.c:807 is a stub.

[New LWP 6894]
[New LWP 6895]
Error reading shortcut keys: Attempted to read past end of file.
ERROR[/home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/world/map.c:228 (map_get_first_element_at)]: Trying to access element outside of range

Thread 1 "openrct2" received signal SIGSEGV, Segmentation fault.
0x00005555559ec1ee in place_maze_design (flags=0 '\000', rideIndex=34 '"', 
    mazeEntry=0, x=2016, y=-1440, z=160)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/ride/track_design.c:1553
1553			if (supportZ > mapElement->base_height) {
(gdb) bt full
#0  0x00005555559ec1ee in place_maze_design (flags=0 '\000', rideIndex=34 '"', 
    mazeEntry=0, x=2016, y=-1440, z=160)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/ride/track_design.c:1553
        mapElement = 0x0
        supportZ = 24 '\030'
        cost = 270
        ride = 0x5555563ed6e0 <gRideList+20672>
        price = 270
#1  0x00005555559ec653 in game_command_place_maze_design (eax=0x7fffffffd87c, 
    ebx=0x7fffffffd878, ecx=0x7fffffffd874, edx=0x7fffffffd870, 
    esi=0x7fffffffd86c, edi=0x7fffffffd868, ebp=0x7fffffffd890)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/ride/track_design.c:1654
No locals.
#2  0x00005555556df12b in game_do_command_p (command=50, eax=0x7fffffffd87c, 
    ebx=0x7fffffffd878, ecx=0x7fffffffd874, edx=0x7fffffffd870, 
    esi=0x7fffffffd86c, edi=0x7fffffffd868, ebp=0x7fffffffd890)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/game.c:513
        cost = 270
        flags = 0
        original_ebx = 0
---Type <return> to continue, or q <return> to quit---
        original_edx = 34
        original_esi = 50
        original_edi = 160
        original_ebp = 0
#3  0x00005555556defd7 in game_do_command (eax=2016, ebx=0, ecx=-1440, edx=34, 
    esi=50, edi=160, ebp=0)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/game.c:460
No locals.
#4  0x00005555559ea50c in track_design_place_maze (td6=0x55555938fc80, x=1824, 
    y=2176, z=160, rideIndex=34 '"')
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/ride/track_design.c:984
        bl = 0 '\000'
        cost = 0
        maze_entry = 0
        rotation = 1 '\001'
        mapCoord = {x = 2016, y = -1440}
        maze = 0x55555938db18
#5  0x00005555559eb4a4 in sub_6D01B3 (td6=0x55555938fc80, bl=1 '\001', 
    rideIndex=34 '"', x=1824, y=2176, z=160)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/ride/track_design.c:1286
---Type <return> to continue, or q <return> to quit---
        track_place_success = 0 '\000'
        scenery = 0x2233e45800
#6  0x00005555559ebad0 in place_track_design (x=1824, y=2176, z=160, 
    flags=104 'h', outRideIndex=0x7fffffffd9f0 "\377h \a\200\b\240")
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/ride/track_design.c:1444
        td6 = 0x55555938fc80
        rideEntryObject = 0x55555938fcf0
        entryType = 0 '\000'
        entryIndex = 79 'O'
        rideIndex = 34 '"'
        rideColour = 0 '\000'
        createRideResult = 0
        ride = 0x5555563ed6e0 <gRideList+20672>
        __func__ = "place_track_design"
        cost = 0
        num_circuits = 0 '\000'
#7  0x00005555559ec5af in game_command_place_track_design (eax=0x7fffffffdac8, 
    ebx=0x7fffffffdacc, ecx=0x7fffffffdad0, edx=0x7fffffffdad4, 
    esi=0x7fffffffdad8, edi=0x7fffffffdadc, ebp=0x7fffffffdae0)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/ride/track_design.c:1644
        x = 1824
---Type <return> to continue, or q <return> to quit---
        y = 2176
        z = 160
        flags = 104 'h'
        rideIndex = 255 '\377'
#8  0x00005555556df12b in game_do_command_p (command=48, eax=0x7fffffffdac8, 
    ebx=0x7fffffffdacc, ecx=0x7fffffffdad0, edx=0x7fffffffdad4, 
    esi=0x7fffffffdad8, edi=0x7fffffffdadc, ebp=0x7fffffffdae0)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/game.c:513
        cost = -2147483648
        flags = 105
        original_ebx = 105
        original_edx = 0
        original_esi = 48
        original_edi = 160
        original_ebp = 0
#9  0x0000555555aa0cf9 in window_track_place_attempt_placement (
    td6=0x55555938fc80, x=1824, y=2176, z=160, bl=105, cost=0x7fffffffdb40, 
    rideIndex=0x7fffffffdb39 "\" \a\200\b\240")
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/windows/track_place.c:439
        eax = 1824
        ebx = 104
---Type <return> to continue, or q <return> to quit---
        ecx = 2176
        edx = 0
        esi = 48
        edi = 160
        ebp = 0
        result = -2147483648
#10 0x0000555555aa07c6 in window_track_place_toolupdate (
    w=0x55555633e620 <g_window_list+1248>, widgetIndex=6, x=234, y=158)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/windows/track_place.c:278
        rideIndex = 34 '"'
        i = 6
        mapX = 1824
        mapY = 2176
        mapZ = 160
        cost = -2147483648
#11 0x00005555556fa850 in window_event_tool_update_call (
    w=0x55555633e620 <g_window_list+1248>, widgetIndex=6, x=234, y=158)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/interface/window.c:1953
No locals.
#12 0x00005555556e35d5 in process_mouse_tool (x=234, y=158)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/input.---Type <return> to continue, or q <return> to quit---
c:1147
        w = 0x55555633e620 <g_window_list+1248>
#13 0x00005555556e0c29 in game_handle_input ()
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/input.c:145
        x = 234
        y = 158
        state = 0
#14 0x00005555556decc0 in game_update ()
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/game.c:363
        i = 1
        numUpdates = 1
#15 0x000055555573ed29 in rct2_update ()
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/rct2.c:403
        tickCount = 82519
#16 0x0000555555abfdc7 in OpenRCT2::RunFixedFrame ()
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/OpenRCT2.cpp:470
        currentTick = 82512
        ticksElapsed = 18
#17 0x0000555555abfc7e in OpenRCT2::RunGameLoop ()
---Type <return> to continue, or q <return> to quit---
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/OpenRCT2.cpp:427
No locals.
#18 0x0000555555abf638 in openrct2_launch ()
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/OpenRCT2.cpp:299
No locals.
#19 0x0000555555739d7f in main (argc=1, argv=0x7fffffffdea8)
    at /home/michael/Programma's/Code/CLionProjects/OpenRCT2/src/openrct2/platform/posix.c:60
        run_game = 1
```

**Comment by rwjuk** [comment]
Looks interesting - will try to replicate and investigate.

**Comment by Chaosmeister** [comment]
This minimaze has a lot of tiles scattered around the map:

![image](https://user-images.githubusercontent.com/13346344/29589209-b3f27340-8794-11e7-9d9b-7087e3458a9b.png)
