### ISSUE TITLE
Division by zero with OpenGL renderer

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6189]
**OS:** Linux
**Commit/Build:** c75be4865

Use this patch to easily trigger:
```diff
diff --git a/src/openrct2-ui/drawing/engines/opengl/OpenGLDrawingEngine.cpp b/src/openrct2-ui/drawing/engines/opengl/OpenGLDrawingEngine.cpp
index 9f1c182a9..a4dc460ed 100644
--- a/src/openrct2-ui/drawing/engines/opengl/OpenGLDrawingEngine.cpp
+++ b/src/openrct2-ui/drawing/engines/opengl/OpenGLDrawingEngine.cpp
@@ -676,6 +676,8 @@ void OpenGLDrawingContext::DrawSprite(uint32 image, sint32 x, sint32 y, uint32 t
     command.texMaskAtlas = 0;
     command.texMaskBounds = { 0.0f, 0.0f, 0.0f };
     command.texPaletteAtlas = texture2.index;
+    assert((texture2.bounds.z - texture2.bounds.x) != 0);
+    assert((texture2.bounds.w - texture2.bounds.y) != 0);
     command.texPaletteBounds = {
         texture2.normalizedBounds.x,
         texture2.normalizedBounds.y,
```

**Steps to reproduce:**
1. Launch OpenRCT2 with renderer set to OpenGL

Here's the full backtrace:
```
#4  0x00000001001b75a9 in OpenGLDrawingContext::DrawSprite (this=0x1014ed710, image=2200, x=-1408, y=1200, tertiaryColour=0) at /home/janisozaur/workspace/OpenRCT2/src/openrct2-ui/drawing/engines/opengl/OpenGLDrawingEngine.cpp:679
        g1Id = 2200
        g1Element = 0x7f9ba8076e50
        zoomLevel = 1 '\001'
        drawOffsetX = -32
        drawOffsetY = 0
        drawWidth = 64
        drawHeight = 31
        left = -46
        top = -13
        zoom_mask = -1
        right = 18
        bottom = 18
        texture = {
          index = 0, 
          slot = 1021, 
          bounds = {
            {
              x = 1856, 
              s = 1856, 
              r = 1856
            }, 
            {
              y = 1984, 
              t = 1984, 
              g = 1984
            }, 
            {
              z = 1920, 
              p = 1920, 
              b = 1920
            }, 
            {
              w = 2015, 
              q = 2015, 
              a = 2015
            }
          }, 
          normalizedBounds = {
            {
              x = 0.90625, 
              s = 0.90625, 
              r = 0.90625
            }, 
            {
              y = 0.96875, 
              t = 0.96875, 
              g = 0.96875
            }, 
            {
              z = 0.9375, 
              p = 0.9375, 
              b = 0.9375
            }, 
            {
              w = 0.983886719, 
              q = 0.983886719, 
              a = 0.983886719
            }
          }
        }
        special = false
        texture2 = {
          index = 0, 
          slot = 0, 
          bounds = {
            {
              x = 0, 
              s = 0, 
              r = 0
            }, 
            {
              y = 0, 
              t = 0, 
              g = 0
            }, 
            {
              z = 0, 
              p = 0, 
              b = 0
            }, 
            {
              w = 0, 
              q = 0, 
              a = 0
            }
          }, 
          normalizedBounds = {
            {
              x = 0, 
              s = 0, 
              r = 0
            }, 
            {
              y = 0, 
              t = 0, 
              g = 0
            }, 
            {
              z = 0, 
              p = 0, 
              b = 0
            }, 
            {
              w = 0, 
              q = 0, 
              a = 0
            }
          }
        }
        command = {
          clip = {
            {
              x = 0, 
              s = 0, 
              r = 0
            }, 
            {
              y = 0, 
              t = 0, 
              g = 0
            }, 
            {
              z = 18, 
              p = 18, 
              b = 18
            }, 
            {
              w = 1001, 
              q = 1001, 
              a = 1001
            }
          }, 
          texColourAtlas = 0, 
          texColourBounds = {
            {
              x = 0.90625, 
              s = 0.90625, 
              r = 0.90625
            }, 
            {
              y = 0.96875, 
              t = 0.96875, 
              g = 0.96875
            }, 
            {
              z = 0.9375, 
              p = 0.9375, 
              b = 0.9375
            }, 
            {
              w = 0.983886719, 
              q = 0.983886719, 
              a = 0.983886719
            }
          }, 
          texMaskAtlas = 0, 
          texMaskBounds = {
            {
              x = 0, 
              s = 0, 
              r = 0
            }, 
            {
              y = 0, 
              t = 0, 
              g = 0
            }, 
            {
              z = 0, 
              p = 0, 
              b = 0
            }, 
            {
              w = 0, 
              q = 0, 
              a = 0
            }
          }, 
          texPaletteAtlas = 0, 
          texPaletteBounds = {
            {
              x = 1.40129846e-45, 
              s = 1.40129846e-45, 
              r = 1.40129846e-45
            }, 
            {
              y = -nan(0x7fc9f0), 
              t = -nan(0x7fc9f0), 
              g = -nan(0x7fc9f0)
            }, 
            {
              z = 4.59163468e-41, 
              p = 4.59163468e-41, 
              b = 4.59163468e-41
            }, 
            {
              w = 3.79905242e-38, 
              q = 3.79905242e-38, 
              a = 3.79905242e-38
            }
          }, 
          flags = 1, 
          colour = {
            {
              x = 0, 
              s = 0, 
              r = 0
            }, 
            {
              y = 0, 
              t = 0, 
              g = 0
            }, 
            {
              z = 3.84652617e-38, 
              p = 3.84652617e-38, 
              b = 3.84652617e-38
            }, 
            {
              w = 1.40129846e-45, 
              q = 1.40129846e-45, 
              a = 1.40129846e-45
            }
          }, 
          bounds = {
            {
              x = 1798797, 
              s = 1798797, 
              r = 1798797
            }, 
            {
              y = 0, 
              t = 0, 
              g = 0
            }, 
            {
              z = 0, 
              p = 0, 
              b = 0
            }, 
            {
              w = 0, 
              q = 0, 
              a = 0
            }
          }, 
          mask = -14256
        }
        __PRETTY_FUNCTION__ = "virtual void OpenGLDrawingContext::DrawSprite(uint32, sint32, sint32, uint32)"
#5  0x00000001003019c4 in gfx_draw_sprite (dpi=0x7fffffffc9f0, image=2200, x=-1408, y=1200, tertiary_colour=0) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/drawing/NewDrawing.cpp:269
        dc = 0x1014ed710
#6  0x00000001002270e6 in paint_ps_image (dpi=0x7fffffffc9f0, ps=0x100e62dc8 <gPaintStructs+136>, imageId=2200, x=-1408, y=1200) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/paint/paint.c:986
No locals.
#7  0x0000000100226a41 in paint_draw_structs (dpi=0x7fffffffc9f0, ps=0x100e62dc8 <gPaintStructs+136>, viewFlags=1024) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/paint/paint.c:898
        x = -1408
        y = 1200
        imageId = 2200
        previous_ps = 0x100e62dc8 <gPaintStructs+136>
#8  0x00000001002046be in viewport_paint_column (dpi=0x7fffffffc9f0, viewFlags=1024) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/interface/viewport.c:750
        ps = {
          image_id = 0, 
          {
            tertiary_colour = 0, 
            colour_image_id = 0
          }, 
          bound_box_x = 0, 
          bound_box_y = 0, 
          bound_box_z = 0, 
          bound_box_z_end = 0, 
          bound_box_x_end = 0, 
          bound_box_y_end = 0, 
          x = 0, 
          y = 0, 
          quadrant_index = 0, 
          flags = 0 '\000', 
          quadrant_flags = 0 '\000', 
          attached_ps = 0x0, 
          var_20 = 0x0, 
          next_quadrant_ps = 0x100e62d40 <gPaintStructs>, 
          sprite_type = 0 '\000', 
          var_29 = 0 '\000', 
          pad_2A = 0, 
          map_x = 0, 
          map_y = 0, 
          mapElement = 0x0
        }
#9  0x00000001002045f3 in viewport_paint (viewport=0x100e3ae80 <g_viewport_list>, dpi=0x7fffffffcac0, left=-1394, top=1213, right=403, bottom=2214) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/interface/viewport.c:732
        dpi2 = {
          bits = 0x1038969f0 "", 
          x = -1394, 
          y = 1213, 
          width = 18, 
          height = 1001, 
          pitch = 1779, 
          zoom_level = 0
        }
        paintRight = -1376
        viewFlags = 1024
        width = 1797
        height = 1001
        bitmask = 65535
        x = -1408
        y = 0
        dpi1 = {
          bits = 0x1038969f0 "", 
          x = -1394, 
          y = 1213, 
          width = 1797, 
          height = 1001, 
          pitch = 0, 
          zoom_level = 0
        }
        rightBorder = 403
#10 0x00000001002042c9 in viewport_render (dpi=0x7fffffffcac0, viewport=0x100e3ae80 <g_viewport_list>, left=-1394, top=1213, right=403, bottom=2214) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/interface/viewport.c:658
No locals.
#11 0x00000001001d43c1 in window_main_paint (w=0x100e3b4c0 <g_window_list>, dpi=0x7fffffffcac0) at /home/janisozaur/workspace/OpenRCT2/src/openrct2-ui/windows/Main.cpp:102
No locals.
#12 0x000000010021022b in window_event_paint_call (w=0x100e3b4c0 <g_window_list>, dpi=0x7fffffffcac0) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/interface/window.c:2079
No locals.
#13 0x000000010020f3b5 in window_draw_single (dpi=0x7fffffffcac0, w=0x100e3b4c0 <g_window_list>, left=0, top=0, right=1797, bottom=1001) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/interface/window.c:1728
        copy = {
          bits = 0x1038969f0 "", 
          x = 0, 
          y = 0, 
          width = 1797, 
          height = 1001, 
          pitch = 0, 
          zoom_level = 0
        }
        overflow = 0
#14 0x000000010020ee2a in window_draw (dpi=0x7fffffffcb60, w=0x100e3b4c0 <g_window_list>, left=0, top=0, right=1797, bottom=1001) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/interface/window.c:1624
        v = 0x100e3b4c0 <g_window_list>
#15 0x00000001001e92c1 in window_draw_all (dpi=0x101516cc0, left=0, top=0, right=1797, bottom=1001) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/drawing/drawing.c:583
        w = 0x100e3b4c0 <g_window_list>
        windowDPI = {
          bits = 0x1038969f0 "", 
          x = 0, 
          y = 0, 
          width = 1797, 
          height = 1001, 
          pitch = 0, 
          zoom_level = 0
        }
#16 0x00000001001b94bf in OpenGLDrawingEngine::PaintWindows (this=0x101516c80) at /home/janisozaur/workspace/OpenRCT2/src/openrct2-ui/drawing/engines/opengl/OpenGLDrawingEngine.cpp:254
No locals.
#17 0x0000000100353dd9 in OpenRCT2::Paint::Painter::Paint (this=0x10121f730, de=0x101516c80) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/paint/Painter.cpp:53
        dpi = 0x101516cc0
#18 0x0000000100301537 in drawing_engine_draw () at /home/janisozaur/workspace/OpenRCT2/src/openrct2/drawing/NewDrawing.cpp:163
No locals.
#19 0x00000001002d54f3 in OpenRCT2::Context::RunFixedFrame (this=0x101220200) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/Context.cpp:602
        currentTick = 35029236
        elapsed = 26
#20 0x00000001002d53e1 in OpenRCT2::Context::RunGameLoop (this=0x101220200) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/Context.cpp:570
        variableFrame = false
        useVariableFrame = false
#21 0x00000001002d51c6 in OpenRCT2::Context::Launch (this=0x101220200) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/Context.cpp:531
No locals.
#22 0x00000001002d42e3 in OpenRCT2::Context::RunOpenRCT2 (this=0x101220200, argc=2, argv=0x7fffffffce58) at /home/janisozaur/workspace/OpenRCT2/src/openrct2/Context.cpp:156
No locals.
#23 0x00000001001a3aa5 in main (argc=2, argv=0x7fffffffce58) at /home/janisozaur/workspace/OpenRCT2/src/openrct2-ui/Ui.cpp:63
        env = 0x101155e70
        audioContext = 0x101153440
        uiContext = 0x10118e290
        context = 0x101220200
        runGame = 1
```

In this stack trace, you can see `texture2` was zero-initialised, which leads to the described issue.

**Comment by ZehMatt** [comment]
Given that I mainly use OpenGL and I never got a crash I'm gonna assume its fixed.
