### ISSUE TITLE
openrct2-cli segfaults without arguments

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#6490]
**OS:** Linux
**Commit/Build:** 9d5c6a4

`openrct2-cli` without any arguments tries to load the title sequence and will fail, making it segfault. Instead, it should log some helpful message and exit.

**Steps to reproduce:**
1. Setup a clean openrct2 install
2. Launch `openrct2-cli`

Stack trace:
```
#0  0x00007ffff72d13eb in TitleSequencePlayer::PrepareParkForPlayback (this=0x7014d0)
    at ../src/openrct2/title/TitleSequencePlayer.cpp:406
#1  TitleSequencePlayer::LoadParkFromStream (hintPath="SpacekKing.sv6", stream=<optimized out>, this=0x7014d0)
    at ../src/openrct2/title/TitleSequencePlayer.cpp:393
#2  TitleSequencePlayer::ExecuteCommand (command=0x701510, this=0x7014d0)
    at ../src/openrct2/title/TitleSequencePlayer.cpp:294
#3  TitleSequencePlayer::Update (this=0x7014d0) at ../src/openrct2/title/TitleSequencePlayer.cpp:141
#4  0x00007ffff72caa1e in TitleScreen::TryLoadSequence (this=0x61b610)
    at ../src/openrct2/title/TitleScreen.cpp:213
#5  0x00007ffff72cacb5 in TitleScreen::Load (this=0x61b610) at ../src/openrct2/title/TitleScreen.cpp:95
#6  0x00007ffff72cad31 in title_load () at ../src/openrct2/title/TitleScreen.cpp:238
#7  0x00007ffff703aa4f in OpenRCT2::Context::Launch (this=this@entry=0x633320)
    at ../src/openrct2/Context.cpp:444
#8  0x00007ffff703b0d5 in OpenRCT2::Context::RunOpenRCT2 (this=0x633320, argc=<optimized out>, 
    argv=<optimized out>) at ../src/openrct2/Context.cpp:157
#9  0x0000000000400895 in main (argc=1, argv=0x7fffffffe558) at ../src/openrct2-cli/Cli.cpp:38
```

**Comment by IntelOrca** [comment]
I think I fixed this in #7163
