### ISSUE TITLE
Android compiling issues: how can I build Android OpenRCT2

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#6791]
I'm unable to build Android versions of OpenRCT2 myself. I used Android Studio 3.0.1. 

I tried building it multiple times with Android Studio: First it gives and error about using a too old version of Gradle (3.3) and that I have to update it to get it to build and I pressed on "update". After I do that and try to build finally, I get this error: "Error:All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html"

Did I do something wrong or can OpenRCT2-Android only be compiled on old versions of Android Studio?

So, what do I have to do to build Android builds myself? Would it be possible for someone to fix this, so it can build with the newest version of Android Studio and Gradle? Or do I have to build it in a completely other way?

I would like to make some minor adjustments to the OpenRCT2-Android code, but without being able to compile it myself, I can't test it.

@marijnvdwerf @janisozaur ?

**Comment by janisozaur** [comment]
You should not use android studio, just gradle itself.

**Comment by mrtnptrs** [comment]
How exactly? There is no documentation anywhere on the wiki about it. What program should I install for it. What are the exact steps?

**Comment by janisozaur** [comment]
```
$ cd src/openrct2-android
$ ./gradlew build
```

**Comment by mrtnptrs** [comment]
Ok, and where exactly do I have to type that in?

**Comment by janisozaur** [comment]
In your shell

**Comment by mrtnptrs** [comment]
What shell exactly or how do I open it? (as you see, I'm a real newbie regarding this, just interested in this.)

**Comment by mrtnptrs** [comment]
Could it be that I need Java to be installed to be able do this?

**Comment by janisozaur** [comment]
You will need android SDK and NDK installed and `$ANDROID_HOME` set to SDK location. Gradle will prompt you to set NDK location it `local.prop` or some other file.

**Comment by mrtnptrs** [comment]
Aren't the Android SDK and NDK automaticly installed with Android Studio. How do I set $ANDROID_HOME?

**Comment by mrtnptrs** [comment]
![image](https://user-images.githubusercontent.com/4948213/33688171-c1d50984-dada-11e7-8bcf-f47d1c746777.png)

Getting that at the moment, of course.

**Comment by janisozaur** [comment]
No idea how to do that on Windows, you should follow Android SDK setup instructions.

**Comment by mrtnptrs** [comment]
I already have the Android SDK installed when I installed Android Studio, it seems to be the best/only way to get the Android SDK. So, there are no setup instructions...... @marijnvdwerf  Weet jij het misschien?

**Comment by Broxzier** [comment]
`JAVA_HOME` is set for the JDK (not the SDK), make sure you have this installed.

**Comment by mrtnptrs** [comment]
Ok, after installing JDK 9.0.1 (the latest version) I got the following error:
```
* What went wrong:
Could not determine java version from '9.0.1'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: Could not determine java version from '9.0.1'.
        at org.gradle.api.JavaVersion.toVersion(JavaVersion.java:70)
        at org.gradle.api.JavaVersion.current(JavaVersion.java:80)
        at org.gradle.internal.jvm.UnsupportedJavaRuntimeException.assertUsingVersion(UnsupportedJavaRuntimeException.java:29)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:32)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

What can I do to fix this?

**Comment by marijnvdwerf** [comment]
I just used Android Studio while developing the Android port. Make sure you have the ndk components installed though.

**Comment by mrtnptrs** [comment]
@marijnvdwerf Is it also "compatible" with the newest version of Android Studio? Because, as I said earlier, it doesn't seem to work with it. I will dubblecheck if the NDK is installed.
