### ISSUE TITLE
Possibly invalid check for peeps while unloading passengers

### ISSUE THREAD

**Issue by janisozaur** [OpenRCT2/OpenRCT2#7393]
https://github.com/OpenRCT2/OpenRCT2/blob/4c9d047b5299157d22f009b18f3be92fdea6e6a9/src/openrct2/ride/Vehicle.cpp#L4095-L4107

This only checks for evenly-numbered peeps, while it also unloads oddly-numbered peeps.

This can trigger an assertion about getting sprite 65535, as evident in 
[Howdy.sv6.txt](https://github.com/OpenRCT2/OpenRCT2/files/1889513/Howdy.sv6.txt) submitted by https://gitter.im/OpenRCT2/OpenRCT2/non-dev?at=5acb34667c3a01610dc2046e

**Comment by Gymnasiast** [comment]
This also appears to happen when boarding.

**Comment by duncanspumpkin** [comment]
That bit of code is correct. This is for all rides which work in pairs. Something must be clearing the is used in pairs flag (aka `num_seats & (1<<7)`)

**Comment by duncanspumpkin** [comment]
Objects have been built without the flag being set. We will need to rebuild all rides that are used in pairs.

**Comment by IntelOrca** [comment]
@duncanspumpkin We just need to default the flag to true in OpenRCT2.

**Comment by Gymnasiast** [comment]
https://github.com/OpenRCT2/OpenRCT2/pull/7395

**Comment by janisozaur** [comment]
I'm going to re-open this, as the assertion still gets hit in the linked save, so it might require some load-time fixing (e.g. removing the uneven peep) or changing this condition

**Comment by janisozaur** [comment]
Here's another park that crashes in a very similar way: 
[Oasis Server Map crashy.sv6.xz.txt](https://github.com/OpenRCT2/OpenRCT2/files/1891951/Oasis.Server.Map.crashy.sv6.xz.txt)

```
>>> bt full
#0  0x000000000074dec9 in peep_update_ride_sub_state_7 (peep=0x13c7740 <_spriteList+7424>) at ../src/openrct2/peep/Peep.cpp:3518
        y = 2780
        exit_direction = 1 '\001'
        exitLocation = {
          x = 226, 
          y = 88, 
          z = 14, 
          direction = 3 '\003'
        }
        x = 7280
        z = 14
        load_position = 9 '\t'
        ride = 0x1156a78 <gRideList+51256>
        vehicle = 0x145df40 <_spriteList+623872>
        ride_station = 0 '\000'
        ride_entry = 0x4ab1b48
        vehicle_entry = 0x4ab1b62
        __PRETTY_FUNCTION__ = "void peep_update_ride_sub_state_7(rct_peep*)"
        exitLocation = {
          x = 7699726, 
          y = 0, 
          z = 0, 
          direction = 0 '\000'
        }
        z = 32767
        exit_direction = 69 'E'
        x = -1
        y = -13696
        tile_element = 0x141a240 <_spriteList+346112>
        station_direction = 255 '\377'
        vehicle_type = 0x7fffffffca80
        cl = 0 '\000'
        ch = 0 '\000'
        exit_x = 0
        exit_y = 0
#1  0x0000000000750630 in peep_update_ride (peep=0x13c7740 <_spriteList+7424>) at ../src/openrct2/peep/Peep.cpp:4540
        __PRETTY_FUNCTION__ = "void peep_update_ride(rct_peep*)"
#2  0x00000000007560ff in peep_update (peep=0x13c7740 <_spriteList+7424>) at ../src/openrct2/peep/Peep.cpp:7568
        stepsToTake = 128
        carryCheck = 271
        __PRETTY_FUNCTION__ = "void peep_update(rct_peep*)"
#3  0x0000000000747cbb in peep_update_all () at ../src/openrct2/peep/Peep.cpp:574
        i = 2076
        spriteIndex = 3310
        peep = 0x13c7740 <_spriteList+7424>
#4  0x0000000000675dd1 in game_logic_update () at ../src/openrct2/Game.cpp:484
No locals.
#5  0x0000000000675b14 in game_update () at ../src/openrct2/Game.cpp:382
        i = 0
        numUpdates = 1
#6  0x000000000066d0c8 in OpenRCT2::Context::Update (this=0x16ed250) at ../src/openrct2/Context.cpp:806
        currentUpdateTick = 25546661
#7  0x000000000066cf69 in OpenRCT2::Context::RunVariableFrame (this=0x16ed250) at ../src/openrct2/Context.cpp:763
        currentTick = 25546661
        draw = true
        elapsed = 17
#8  0x000000000066cd57 in OpenRCT2::Context::RunFrame (this=0x16ed250) at ../src/openrct2/Context.cpp:700
        useVariableFrame = true
#9  0x000000000066ccd3 in OpenRCT2::Context::RunGameLoop (this=0x16ed250) at ../src/openrct2/Context.cpp:675
No locals.
#10 0x000000000066cb02 in OpenRCT2::Context::Launch (this=0x16ed250) at ../src/openrct2/Context.cpp:651
No locals.
#11 0x000000000066b89f in OpenRCT2::Context::RunOpenRCT2 (this=0x16ed250, argc=2, argv=0x7fffffffce48) at ../src/openrct2/Context.cpp:173
No locals.
#12 0x00000000005ac117 in main (argc=2, argv=0x7fffffffce48) at ../src/openrct2-ui/Ui.cpp:60
        env = 0x1677d20
        audioContext = 0x1681810
        uiContext = 0x16b8e20
        context = 0x16ed250
        runGame = 1
>>> frame 0
#0  0x000000000074dec9 in peep_update_ride_sub_state_7 (peep=0x13c7740 <_spriteList+7424>) at ../src/openrct2/peep/Peep.cpp:3518
3518	        sint8 load_position = vehicle_entry->peep_loading_positions[peep->current_seat];
>>> p vehicle_entry->peep_loading_positions
$1 = std::vector of length 0, capacity 0
```

https://github.com/OpenRCT2/OpenRCT2/blob/92ba2dfb01f5e0ec942e65a36225be252943df21/src/openrct2/peep/Peep.cpp#L3518

**Comment by duncanspumpkin** [comment]
Well all the saves created before the fix are broken. There shouldn't be that many I'd say just delete the saves.

**Comment by janisozaur** [comment]
In all the cases posted so far double-closing the offending rides (to force guests out of them) mitigates the issues, but figuring which rides are affected requires debugger.

**Comment by duncanspumpkin** [comment]
Well of course that works but since the source of the bug is now fixed I'd just say that people should mark those saves as broken and move on. I see no reason to add specific code to handle bad saves that were generated for all of 1 days.

**Comment by IntelOrca** [comment]
No recent reports of this so I think it safe to close. We can make the peep code more defensive at some point in the future.
