### ISSUE TITLE
OpenRCT2 Crashing when quitting Scenario editor

### ISSUE THREAD

**Issue by L3mmy** [OpenRCT2/OpenRCT2#7787]
**OS:** Windows 10
**Version:** 0.2.0
**Commit/Build:** 426e106

I like making scenario so i found this bug annoying
Basically, my version of OpenRCT2 will crash when i'll quit the scenario editor after save my file

- [X] Reproducible in RCT2 (vanilla)?
- [ ] Specific to multiplayer?

**Steps to reproduce:**
1. Make a scenario
2. Save it **and** quit

**Screenshots / Video:**
Actually, none, because the game crashes just after you hit the save button
**Save game:**
Works in the Scenatio editor **only**

**Comment by janisozaur** [comment]
```
>>> bt full
#0  window_event_close_call (w=0x55555999a0a0) at ../src/openrct2/interface/Window.cpp:1378
No locals.
#1  0x00007ffff6e7e53c in window_close (window=0x55555999a0a0) at ../src/openrct2/interface/Window.cpp:218
        cls = 0 '\000'
        number = 0
        index = 0
#2  0x00005555556df0b2 in window_text_input_mouseup (w=0x55555999a0a0, widgetIndex=4) at ../src/openrct2-ui/windows/TextInput.cpp:186
        calling_w = 0x555555fe6b30
#3  0x00007ffff6e81ace in window_event_mouse_up_call (w=0x55555999a0a0, widgetIndex=4) at ../src/openrct2/interface/Window.cpp:1385
No locals.
#4  0x000055555564d665 in input_state_widget_pressed (x=660, y=444, state=2, widgetIndex=4, w=0x55555999a0a0, widget=0x5555559691e0 <window_text_input_widgets+128>) at ../src/openrct2-ui/input/MouseInput.cpp:1354
        cursor_w_class = 113 'q'
        cursor_w_number = 0
        cursor_widgetIndex = 4
        cursor_w = 0x55555999a0a0
#5  0x000055555564ae64 in game_handle_input_mouse (x=660, y=444, state=2) at ../src/openrct2-ui/input/MouseInput.cpp:333
        w = 0x55555999a0a0
        widget = 0x5555559691e0 <window_text_input_widgets+128>
        widgetIndex = 4
#6  0x000055555564a677 in game_handle_input () at ../src/openrct2-ui/input/MouseInput.cpp:119
        x = 660
        y = 444
        state = 2
#7  0x0000555555628cb5 in WindowManager::HandleInput (this=0x5555559ff870) at ../src/openrct2-ui/WindowManager.cpp:457
No locals.
#8  0x00007ffff6ded9d2 in context_handle_input () at ../src/openrct2/Context.cpp:1244
        windowManager = 0x5555559ff870
#9  0x00007ffff6e08998 in OpenRCT2::GameState::Update (this=0x555555fb6fe0) at ../src/openrct2/GameState.cpp:173
        numUpdates = 1
#10 0x00007ffff6df280d in OpenRCT2::Context::Update (this=0x555555d8f080) at ../src/openrct2/Context.cpp:965
        currentUpdateTick = 14089000
#11 0x00007ffff6df25f6 in OpenRCT2::Context::RunVariableFrame (this=0x555555d8f080) at ../src/openrct2/Context.cpp:920
        currentTick = 14089000
        draw = true
        elapsed = 17
#12 0x00007ffff6df2313 in OpenRCT2::Context::RunFrame (this=0x555555d8f080) at ../src/openrct2/Context.cpp:855
        useVariableFrame = true
#13 0x00007ffff6df228f in OpenRCT2::Context::RunGameLoop (this=0x555555d8f080) at ../src/openrct2/Context.cpp:830
No locals.
#14 0x00007ffff6df20a5 in OpenRCT2::Context::Launch (this=0x555555d8f080) at ../src/openrct2/Context.cpp:806
No locals.
#15 0x00007ffff6df00d1 in OpenRCT2::Context::RunOpenRCT2 (this=0x555555d8f080, argc=1, argv=0x7fffffffd288) at ../src/openrct2/Context.cpp:211
No locals.
#16 0x0000555555618357 in main (argc=1, argv=0x7fffffffd288) at ../src/openrct2-ui/Ui.cpp:60
        env = std::shared_ptr<OpenRCT2::IPlatformEnvironment> (use count 8, weak count 0) = {
          get() = 0x5555559bf5b0
        }
        audioContext = std::shared_ptr<OpenRCT2::Audio::IAudioContext> (use count 2, weak count 0) = {
          get() = 0x5555559c9ba0
        }
        uiContext = std::shared_ptr<OpenRCT2::Ui::IUiContext> (use count 4, weak count 0) = {
          get() = 0x555555a01070
        }
        context = std::unique_ptr<OpenRCT2::IContext> = {
          get() = 0x555555d8f080
        }
        runGame = 1
>>> p *w
$2 = {
  event_handlers = 0x40007, 
  viewport = 0x0, 
  enabled_widgets = 0, 
  disabled_widgets = 0, 
  pressed_widgets = 0, 
  hold_down_widgets = 0, 
  widgets = 0x0, 
  x = 0, 
  y = 0, 
  width = 0, 
  height = 0, 
  min_width = 0, 
  max_width = 3, 
  min_height = 2, 
  max_height = 0, 
  number = 0, 
  flags = 0, 
  scrolls = {[0] = {
      flags = 0, 
      h_left = 0, 
      h_right = 0, 
      h_thumb_left = 0, 
      h_thumb_right = 0, 
      v_top = 0, 
      v_bottom = 0, 
      v_thumb_top = 0, 
      v_thumb_bottom = 0
    }, [1] = {
      flags = 0, 
      h_left = 0, 
      h_right = 0, 
      h_thumb_left = 0, 
      h_thumb_right = 0, 
      v_top = 0, 
      v_bottom = 0, 
      v_thumb_top = 0, 
      v_thumb_bottom = 0
    }, [2] = {
      flags = 0, 
      h_left = 0, 
      h_right = 0, 
      h_thumb_left = 0, 
      h_thumb_right = 0, 
      v_top = 0, 
      v_bottom = 0, 
      v_thumb_top = 0, 
      v_thumb_bottom = 0
    }}, 
  list_item_positions = "\000\000\002\000UC", '\000' <repeats 64 times>, "P-", '\000' <repeats 62 times>, "\003\000\003", '\000' <repeats 63 times>..., 
  no_list_items = 0, 
  pad_478 = 0, 
  selected_list_item = 0, 
  pad_47C = 0, 
  pad_47E = 0, 
  {
    viewport_focus_coordinates = {
      var_480 = 0, 
      x = 0, 
      y = 0, 
      z = 0, 
      rotation = 0 '\000', 
      zoom = 0 '\000', 
      width = 0, 
      height = 0
    }, 
    viewport_focus_sprite = {
      var_480 = 0, 
      sprite_id = 0, 
      pad_484 = 0 '\000', 
      type = 0 '\000', 
      pad_486 = 0, 
      rotation = 0 '\000', 
      zoom = 0 '\000'
    }, 
    campaign = {
      campaign_type = 0, 
      no_weeks = 0, 
      ride_id = 0, 
      pad_486 = 0
    }, 
    new_ride = {
      selected_ride_id = 0, 
      highlighted_ride_id = 0, 
      pad_484 = 0, 
      pad_486 = 0, 
      selected_ride_countdown = 0
    }, 
    news = {
      var_480 = 0, 
      var_482 = 0, 
      var_484 = 0, 
      var_486 = 0, 
      var_488 = 0
    }, 
    map = {
      rotation = 0, 
      var_482 = 0, 
      var_484 = 0, 
      var_486 = 0, 
      var_488 = 0
    }, 
    ride = {
      view = 0, 
      var_482 = 0, 
      var_486 = 0
    }, 
    scenery = {
      selected_scenery_id = 0, 
      hover_counter = 0
    }, 
    track_list = {
      track_list_being_updated = false, 
      reload_track_designs = false
    }, 
    error = {
      var_480 = 0
    }
  }, 
  page = 0, 
  {
    picked_peep_old_x = 0, 
    vehicleIndex = 0, 
    numberOfStaff = 0, 
    var_48C = 0
  }, 
  frame_no = 0, 
  list_information_type = 0, 
  {
    picked_peep_frame = 0, 
    var_492 = 0
  }, 
  {
    highlighted_item = 0, 
    ride_colour = 0, 
    research_item = 0x0, 
    object_entry = 0x0, 
    highlighted_scenario = 0x0, 
    {
      var_494 = 0, 
      var_496 = 0
    }
  }, 
  var_498 = '\000' <repeats 19 times>, 
  selected_tab = 0, 
  var_4AE = 0, 
  viewport_target_sprite = 0, 
  saved_view_x = 0, 
  saved_view_y = 0, 
  classification = 0 '\000', 
  pad_4B7 = 0 '\000', 
  var_4B8 = 0 '\000', 
  var_4B9 = 0 '\000', 
  colours = "\000\000\000\000\000", 
  visibility = 0 '\000', 
  viewport_smart_follow_sprite = 0
}
```
https://github.com/OpenRCT2/OpenRCT2/blob/ab20dcde9f92042544cfc8077e6be9d22000cafa/src/openrct2/interface/Window.cpp#L1378

**Comment by moonheart08** [comment]
I have the same issue. Shall i make a trace?

**Comment by janisozaur** [comment]
That shouldn't be needed, it is easily reproducible.

**Comment by L3mmy** [comment]
![image](https://user-images.githubusercontent.com/41308252/44956353-dbd72a80-aec2-11e8-8c87-ed5c57095eab.png)
Nowadays, it gave me this error message

**Comment by Broxzier** [comment]
Can you please describe exactly how you save and quit from the scenario editor? This isn't happening for me when I save it as a landscape and then quit via the floppy-disk dropdown menu (on a5cbcb4).

**Comment by Derpercoaster** [comment]
This is still happening. In my experience, it only happens if you've spent a long time in the editor, which suggests a memory leak (maybe?) of some sort. When it happens to me, I can usually successfully quit to the main menu, but clicking any buttons on the main menu afterwards crashes the game and, if you click the new scenario button, causes some text in the scenario list to appear buggy. Waiting a while does not avoid the crash. I can never get a screenshot before it vanishes.
