### ISSUE TITLE
Game crashes in Bumbly Beach and others

### ISSUE THREAD

**Issue by altiereslima** [OpenRCT2/OpenRCT2#8003]
**OS:** [ Windows 10]
**Version:** [0.2.1]
**Commit/Build:** [a6a5e3e]

placing objects

[Dump-Save game.zip](https://github.com/OpenRCT2/OpenRCT2/files/2390352/Dump-Save.game.zip)
![sem titulo](https://user-images.githubusercontent.com/18044879/45651819-fc010f00-baa8-11e8-8b81-15354ba5a8f7.png)

**Comment by myn0k** [comment]
[5c267a82-df3b-4fc9-a0e3-1088d0ef7937(a6a5e3e_x86-64).txt](https://github.com/OpenRCT2/OpenRCT2/files/2390428/5c267a82-df3b-4fc9-a0e3-1088d0ef7937.a6a5e3e_x86-64.txt)

**Comment by myn0k** [comment]
_dj khaled voice_ Anotha' one

[6d8ae401-465e-46de-9e4b-87e8afdcaea1(856f29a_x86-64).txt](https://github.com/OpenRCT2/OpenRCT2/files/2391232/6d8ae401-465e-46de-9e4b-87e8afdcaea1.856f29a_x86-64.txt)

**Comment by AaronVanGeffen** [comment]
```
Thread 1 "openrct2" received signal SIGSEGV, Segmentation fault.
0x0000555555efb1f5 in SmallSceneryElement::SetEntryIndex(unsigned char) ()
(gdb) bt
#0  0x0000555555efb1f5 in SmallSceneryElement::SetEntryIndex(unsigned char) ()
#1  0x0000555555efaff4 in SmallSceneryPlace(short, short, unsigned short, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char, unsigned char) ()
#2  0x0000555555efa50f in game_command_place_scenery(int*, int*, int*, int*, int*, int*, int*) ()
#3  0x000055555590c4d2 in game_do_command_p(unsigned int, int*, int*, int*, int*, int*, int*, int*) ()
#4  0x000055555590bffd in game_do_command(int, int, int, int, int, int, int) ()
#5  0x00005555558eb4b7 in try_place_ghost_scenery(LocationXY16, unsigned int, unsigned int, unsigned int, unsigned short) ()
#6  0x00005555558e96a9 in top_toolbar_tool_update_scenery(short, short) ()
#7  0x00005555558e5f6d in window_top_toolbar_tool_update(rct_window*, short, int, int) ()
#8  0x00005555559903e3 in window_event_tool_update_call(rct_window*, short, int, int) ()
#9  0x000055555582b259 in process_mouse_tool(int, int) ()
#10 0x000055555582a7c7 in game_handle_input() ()
#11 0x00005555558013e1 in WindowManager::HandleInput() ()
#12 0x00005555558f8483 in context_handle_input() ()
#13 0x0000555555910af7 in OpenRCT2::GameState::Update() ()
#14 0x0000555555901fa3 in OpenRCT2::Context::Update() ()
#15 0x0000555555901c01 in OpenRCT2::Context::RunVariableFrame() ()
#16 0x0000555555901aea in OpenRCT2::Context::RunFrame() ()
#17 0x00005555559019a1 in OpenRCT2::Context::RunGameLoop() ()
#18 0x0000555555901907 in OpenRCT2::Context::Launch() ()
#19 0x00005555558faa39 in OpenRCT2::Context::RunOpenRCT2(int, char const**) ()
#20 0x00005555557ebd17 in main ()
```
