### ISSUE TITLE
Game Crash when Mirroring Saved Ride Design

### ISSUE THREAD

**Issue by rpstester** [OpenRCT2/OpenRCT2#8535]
**OS:** Windows 10
**Version:** 0.2.1
**Commit/Build:** 8d9fcb7

The last thing I clicked was the mirror button when trying to place a saved car ride in Diamond Heights.  I started DH from the beginning (original scenario from RCT1).  I had played other scenarios on this game session.  

I have logged an issue and attached a dump file as you requested.  I have also attached the last auto-save before the game crashed.  

**Steps to reproduce:**
Unknown  

**Dump file**
[0a88cad3-e9a7-44ba-a91f-47664bf7394e(8d9fcb7_x86-64).zip](https://github.com/OpenRCT2/OpenRCT2/files/2711078/0a88cad3-e9a7-44ba-a91f-47664bf7394e.8d9fcb7_x86-64.zip)

**Save game:**
[autosave_2018-12-26_19-27-05.zip](https://github.com/OpenRCT2/OpenRCT2/files/2711080/autosave_2018-12-26_19-27-05.zip)

**Comment by rpstester** [comment]
Sadly, loading the same saved game, selecting the same car ride, and clicking on mirror crashed the ride again.  So there is a way to reproduce it.

**Comment by rpstester** [comment]
I can mirror other saved car rides just fine.  It looks like this file is from Time Twister.

**Comment by Gymnasiast** [comment]
Could you also upload the track design in question?

**Comment by rpstester** [comment]
[ Pegasus.zip](https://github.com/OpenRCT2/OpenRCT2/files/2719658/Pegasus.zip)
Here you go.

**Comment by janisozaur** [comment]
Reproduces fine with the attached sv6 and track (but not on another scenario)
Crashes via unhandled exception from
https://github.com/OpenRCT2/OpenRCT2/blob/51c88d85fd5658e54914da7964653d903019d7c3/src/openrct2/object/Object.cpp#L40-L43
```
#6  0x0000555558cf3ae6 in Object::GetLegacyData (this=0x611000048ac0) at ../src/openrct2/object/Object.cpp:42
No locals.
#7  0x0000555558cfa997 in object_entry_get_chunk (objectType=5, index=59) at ../src/openrct2/object/ObjectList.cpp:181
        objectIndex = 727
        result = 0x0
        objectMgr = @0x604000021250: {
          _vptr.IObjectManager = 0x55555a7a6c88 <vtable for ObjectManager+16>
        }
        obj = 0x611000048ac0
#8  0x00005555590961f4 in track_design_mirror_scenery (td6=0x6110002dcfc0) at ../src/openrct2/ride/TrackDesign.cpp:496
        entry_type = 5 '\005'
        entry_index = 59 ';'
        scenery_entry = 0x60f00003da10
        scenery = 0x62b000118bee
#9  0x0000555559098eb0 in track_design_mirror (td6=0x6110002dcfc0) at ../src/openrct2/ride/TrackDesign.cpp:660
No locals.
#10 0x00005555588d6f2d in window_track_place_mouseup (w=0x61a00030ba80, widgetIndex=4) at ../src/openrct2-ui/windows/TrackDesignPlace.cpp:218
        intent = {
          _Class = 128 '\200', 
          _Data = std::map with 5397383859 elements<error reading variable: Cannot access memory at address 0xbebebebebebebece>
        }
#11 0x0000555558b9b2ba in window_event_mouse_up_call (w=0x61a00030ba80, widgetIndex=4) at ../src/openrct2/interface/Window.cpp:1438
No locals.
#12 0x000055555854a7d0 in input_state_widget_pressed (x=190, y=103, state=2, widgetIndex=4, w=0x61a00030ba80, widget=0x55555b2b2ec0 <window_track_place_widgets+128>) at ../src/openrct2-ui/input/MouseInput.cpp:1367
        cursor_w_class = 34 '"'
        cursor_w_number = 0
        cursor_widgetIndex = 4
        cursor_w = 0x61a00030ba80
#13 0x000055555853d169 in game_handle_input_mouse (x=190, y=103, state=2) at ../src/openrct2-ui/input/MouseInput.cpp:336
        w = 0x61a00030ba80
        widget = 0x55555b2b2ec0 <window_track_place_widgets+128>
        widgetIndex = 4
#14 0x000055555853a4e5 in game_handle_input () at ../src/openrct2-ui/input/MouseInput.cpp:120
        x = 190
        y = 103
        state = 2
#15 0x000055555845a9ab in WindowManager::HandleInput (this=0x602000001d10) at ../src/openrct2-ui/WindowManager.cpp:460
No locals.
#16 0x0000555558906d57 in context_handle_input () at ../src/openrct2/Context.cpp:1249
        windowManager = 0x602000001d10
#17 0x0000555558963e15 in OpenRCT2::GameState::Update (this=0x602000170710) at ../src/openrct2/GameState.cpp:191
        numUpdates = 1
        realtimeTicksElapsed = <error reading variable realtimeTicksElapsed (Cannot access memory at address 0xffffffffffffff00)>
        didRunSingleFrame = false
#18 0x0000555558920afd in OpenRCT2::Context::Update (this=0x611000011fc0) at ../src/openrct2/Context.cpp:951
        currentUpdateTime = 9189611
#19 0x000055555891f5ed in OpenRCT2::Context::RunVariableFrame (this=0x611000011fc0) at ../src/openrct2/Context.cpp:899
        currentTick = 9189611
        draw = true
        elapsed = 27
#20 0x000055555891c67d in OpenRCT2::Context::RunFrame (this=0x611000011fc0) at ../src/openrct2/Context.cpp:833
        useVariableFrame = true
#21 0x000055555891bee7 in OpenRCT2::Context::RunGameLoop (this=0x611000011fc0) at ../src/openrct2/Context.cpp:808
No locals.
#22 0x000055555891b1e7 in OpenRCT2::Context::Launch (this=0x611000011fc0) at ../src/openrct2/Context.cpp:780
No locals.
#23 0x00005555589102db in OpenRCT2::Context::RunOpenRCT2 (this=0x611000011fc0, argc=2, argv=0x7fffffffda28) at ../src/openrct2/Context.cpp:220
No locals.
#24 0x0000555558407257 in main (argc=2, argv=0x7fffffffda28) at ../src/openrct2-ui/Ui.cpp:60
        env = std::shared_ptr<OpenRCT2::IPlatformEnvironment> (use count 8, weak count 0) = {
          get() = 0x611000000400
        }
        audioContext = std::shared_ptr<OpenRCT2::Audio::IAudioContext> (use count 2, weak count 0) = {
          get() = 0x602000000ff0
        }
        uiContext = std::shared_ptr<OpenRCT2::Ui::IUiContext> (use count 4, weak count 0) = {
          get() = 0x62900000a200
        }
        context = std::unique_ptr<OpenRCT2::IContext> = {
          get() = 0x611000011fc0
        }
        runGame = 1
```
